/**
 * Flight paths, generated by the ROM's own machine.
 *
 * Every route in the game now comes out of the tables in `flightData.js` run
 * through the interpreter in `pathcode.js`: the 22 fly-in blocks behind the
 * 24-entry `db_2A3C` index, the three attack-dive tables, and the challenge
 * rows. The authored heading-delta programs this file used to hold are gone.
 *
 * Two ways to consume a flight:
 *
 * - **Compiled tracks** (`entryPath`, `challengingPath`, `divePath`,
 *   `returnPath`, `captiveEscapePath`): the interpreter runs offline against
 *   a context frozen at build time and emits one sampled point per hardware
 *   frame. `pointOnPath`/`tangentAngle` and `flight.js`'s track walker are
 *   unchanged. Right for any flight whose reactive tokens can be resolved at
 *   launch (fly-ins below the stage-8 gate, challenge fly-throughs).
 *
 * - **Live flights** (`createEntryFlightState`, `createDiveFlightState`,
 *   stepped through `flight.js`'s live-flight API): the scene drives the
 *   interpreter frame by frame with the LIVE context -- the swaying formation
 *   slot as the FB home target, the player's position for the FE/F3/F4
 *   tokens, the scheduler's continuous-bombing flag for the FA loop gate.
 *   This is what the reactive tokens need and what precompilation cannot do.
 */

import {
  ATTACK_PATH_BOSS,
  ATTACK_PATH_RED,
  ATTACK_PATH_YELLOW,
  CHALLENGE_ROWS,
  DB_2A3C,
  DB_2A6C,
  FLY_IN_BLOCKS,
  FLY_IN_BLOCK_COUNT,
  challengeRowWaves,
} from './flightData.js';
import {
  ROM_CANVAS,
  asTrack,
  beginHomeGlide,
  canvasToRaw,
  createFlightState,
  directionToAngle,
  isDespawned,
  rawXToCanvasX,
  rawYToCanvasY,
  stepFlight,
  toCanvas,
} from './pathcode.js';

export { trackDurationMs } from './pathcode.js';

// --------------------------------------------------------- track evaluation

/**
 * Evaluate a track at t in [0, 1].
 *
 * t maps linearly onto the frame samples, and positions between two samples
 * interpolate linearly -- which is exactly what the arcade shows between two
 * adjacent frames of the interpreter.
 */
export function pointOnPath(track, t) {
  const points = track?.points;
  if (!points || points.length === 0) {
    throw new Error('pointOnPath requires a track with at least one point');
  }
  if (points.length === 1) return { ...points[0] };

  const clamped = Math.min(Math.max(t, 0), 1);
  const scaled = clamped * (points.length - 1);
  const index = Math.min(Math.floor(scaled), points.length - 2);
  const local = scaled - index;
  const a = points[index];
  const b = points[index + 1];

  return { x: a.x + (b.x - a.x) * local, y: a.y + (b.y - a.y) * local };
}

/** Heading along the track at t, in radians, from the surrounding samples. */
export function tangentAngle(track, t) {
  const points = track.points;
  const clamped = Math.min(Math.max(t, 0), 1);
  const scaled = clamped * (points.length - 1);
  let index = Math.min(Math.floor(scaled), points.length - 2);
  let a = points[index];
  const b = points[index + 1];
  // A stalled interpreter frame duplicates a sample; look past it for a
  // direction rather than reporting a zero-length tangent.
  while (index > 0 && a.x === b.x && a.y === b.y) {
    index -= 1;
    a = points[index];
  }
  return Math.atan2(b.y - a.y, b.x - a.x);
}

/** Exact track length: the sum of its per-frame steps. */
export function pathLength(track) {
  const points = track.points;
  let total = 0;
  for (let i = 1; i < points.length; i += 1) {
    total += Math.hypot(points[i].x - points[i - 1].x, points[i].y - points[i - 1].y);
  }
  return total;
}

// ------------------------------------------------------------ scale adapter

/**
 * The uniform ROM-canvas-to-screen scale. The interpreter works on the
 * hardware's 224 x 288 portrait canvas; this game's screen is the same
 * aspect at x3. One number, so geometry cannot shear.
 */
export function screenScale(screen) {
  return screen.height / ROM_CANVAS.height;
}

const scalePoint = (point, scale) => ({ x: point.x * scale, y: point.y * scale });
const toRomPoint = (point, scale) => ({ x: point.x / scale, y: point.y / scale });

// ---------------------------------------------------------------- fly-ins

/**
 * How many unique fly-in path blocks exist: 22, the ROM's own count
 * (6 token-bearing combat blocks + 16 token-free fly-throughs).
 */
export const FLY_IN_PATH_COUNT = FLY_IN_BLOCK_COUNT;

/**
 * How many entries the `db_2A3C` index holds: 24. A wave byte's low six bits
 * select one; entries 22/23 reuse two blocks under different spawn variants.
 */
export const FLY_IN_INDEX_COUNT = DB_2A3C.length;

/**
 * The interpreter state for one fly-in launch, seeded the way `f_2916`
 * seeds a slot (gg1-3.s:1855-1894): position and starting angle from the
 * `db_2A6C` variant pair, member picked by wave-byte bit 6 -- which also
 * sets the negate-rotation flag that mirrors every arc the member flies.
 */
export function createEntryFlightState(pathIndex, member, { objectId = 0 } = {}) {
  const entry = DB_2A3C[((pathIndex % FLY_IN_INDEX_COUNT) + FLY_IN_INDEX_COUNT) % FLY_IN_INDEX_COUNT];
  const which = member ? 1 : 0;
  const spawn = DB_2A6C[entry.variant * 2 + which];

  return createFlightState({
    region: FLY_IN_BLOCKS[entry.addr],
    rawX: spawn.rawX,
    rawY: spawn.rawY,
    angle: spawn.rotHi << 8,
    negateRotation: which === 1,
    objectId,
  });
}

/** Where a fly-in member appears, in screen coordinates. */
export function entrySpawnPoint(pathIndex, member, screen) {
  const entry = DB_2A3C[((pathIndex % FLY_IN_INDEX_COUNT) + FLY_IN_INDEX_COUNT) % FLY_IN_INDEX_COUNT];
  const spawn = DB_2A6C[entry.variant * 2 + (member ? 1 : 0)];
  return scalePoint({ x: rawXToCanvasX(spawn.rawX), y: rawYToCanvasY(spawn.rawY) }, screenScale(screen));
}

/** Run a flight offline, collecting one ROM-canvas point per frame. */
function compileFlight(state, context, { maxFrames = 4000, stopWhen } = {}) {
  const points = [toCanvas(state)];
  for (let frame = 0; frame < maxFrames && !state.done; frame += 1) {
    stepFlight(state, context);
    points.push(toCanvas(state));
    if (stopWhen && stopWhen(state)) break;
  }
  return points;
}

/**
 * The compile-time cut for a fly-through: the ROM's despawn margins, plus a
 * top cut (canvas y < -32) so a stream whose closing segment climbs off the
 * top for its full 255 frames does not compile kilometres of invisible
 * track. Port decision: the ROM keeps stepping those frames and FF ends
 * them off screen either way.
 */
function flewOut(state) {
  return isDespawned(state) || toCanvas(state).y < -32;
}

/**
 * Entry flight from a spawn point into a formation slot, compiled.
 *
 * `variant` indexes `db_2A3C`; `mirrored` is wave-byte bit 6 -- the second
 * pair member, spawning at its own `db_2A6C` row with every rotation
 * negated. The block flies to its FB and the homing glide delivers it to
 * `target`, which is frozen at compile time; the scene's live entry flights
 * feed the swaying slot instead. `stage8Switch` resolves the F0 gate.
 *
 * The token-free blocks (indices 6-23) never home in the ROM -- they are
 * challenge fly-throughs ending FF. Until Task 4 replaces the authored
 * caravan rows that still select them for combat, a block that ends without
 * homing is turned home from where it stopped (the FB procedure, glide at
 * the standard `23` tail speed). Interim shim, labelled here.
 */
export function entryPath(variant, target, screen, mirrored = false, { stage8Switch = false } = {}) {
  const scale = screenScale(screen);
  const state = createEntryFlightState(variant, mirrored ? 1 : 0);
  const context = {
    playerX: ROM_CANVAS.width / 2,
    homeTarget: toRomPoint(target, scale),
    stage8Switch,
    stage12Switch: false,
    continuousBombing: false,
  };

  // The six combat blocks fly whole and home themselves; a token-free block
  // pressed into combat duty is cut where it leaves the field and turned
  // home from there rather than compiling its off-screen tail.
  const points = compileFlight(state, context, { stopWhen: flewOut });
  if (!state.homed) {
    beginHomeGlide(state, context);
    points.push(...compileFlight(state, context));
  }
  // Land the final sample exactly on the slot: the snap is within +/-1 raw
  // (2 canvas px) and the scene parks the sprite on the slot anyway.
  points.push(toRomPoint(target, scale));

  return asTrack(points.map((point) => scalePoint(point, scale)));
}

// ----------------------------------------------------------- attack dives

/** Which attack table each enemy type flies. */
const ATTACK_TABLES = {
  zako: { region: ATTACK_PATH_YELLOW, entry: ATTACK_PATH_YELLOW.entryOffset },
  goei: { region: ATTACK_PATH_RED, entry: ATTACK_PATH_RED.entryOffset },
  boss: { region: ATTACK_PATH_BOSS, entry: ATTACK_PATH_BOSS.entryOffset },
};

/**
 * The interpreter state for an attack dive launched from `origin` (screen
 * coordinates): the enemy's live position, angle seed 0x0100 (pointing
 * 90 degrees), negate-rotation from objectId bit 1 (j_108A, gg1-2.s:314-323;
 * escorts inherit their boss's flag by passing `negateRotation` directly).
 * `role: 'capture'` enters the boss table at the solo capture dive.
 */
export function createDiveFlightState(
  enemyType,
  origin,
  screen,
  { objectId = 0, negateRotation, role = 'attack' } = {},
) {
  const table = ATTACK_TABLES[enemyType] ?? ATTACK_TABLES.zako;
  const entry =
    role === 'capture' && enemyType === 'boss' ? ATTACK_PATH_BOSS.captureOffset : table.entry;
  const raw = canvasToRaw(toRomPoint(origin, screenScale(screen)));

  return createFlightState({
    region: table.region,
    pc: entry,
    rawX: raw.rawX,
    rawY: raw.rawY,
    angle: 0x100,
    negateRotation: negateRotation ?? (objectId & 0x02) !== 0,
    objectId,
  });
}

/**
 * Attack dive, compiled: one pass of the type's table with the context
 * frozen at launch -- the player's column for the F3/FE hooks, no continuous
 * bombing, so the FA gate sends it home to `homeTarget` (the slot it left;
 * defaults to `origin`). The live-flight form in the scene re-reads all of
 * that per frame; this compiled form serves the transform trio and tests.
 *
 * `stageIndex` is accepted for API compatibility; dive speed now lives in
 * the tables' own speed nibbles, not a per-stage scalar.
 */
export function divePath(
  origin,
  playerX,
  screen,
  { enemyType = 'zako', stageIndex = 0, stage12Switch = false, homeTarget, objectId } = {},
) {
  void stageIndex;
  const scale = screenScale(screen);
  const state = createDiveFlightState(enemyType, origin, screen, {
    objectId: objectId ?? (origin.x >= screen.width / 2 ? 2 : 0),
  });
  const context = {
    playerX: playerX / scale,
    homeTarget: toRomPoint(homeTarget ?? origin, scale),
    stage8Switch: false,
    stage12Switch,
    continuousBombing: false,
  };

  const points = compileFlight(state, context);
  if (state.homed) points.push(context.homeTarget);

  return asTrack(points.map((point) => scalePoint(point, scale)));
}

// ------------------------------------------------------- challenging stages

/**
 * How many distinct Challenging Stage routes exist: the ROM's 8 rows
 * (`d_challg_stg_dat`), landing on stages 3, 7, 11 ... so the last is not
 * seen until stage 31.
 */
export const CHALLENGING_PATTERN_COUNT = CHALLENGE_ROWS.length;

/**
 * Challenging Stage fly-through, compiled from the real rows.
 *
 * `pattern` selects the row; `offset` is the wave (five per row), whose
 * first wave byte carries the route: index into `db_2A3C` 6-23 (the
 * token-free blocks) plus the variant member and negate-rotation bit. The
 * stream flies its shape and leaves; there is no homing phase at all. Full
 * roster wiring -- both members, transients, launch beats -- is Task 4's
 * stream machine; until then each flight of eight follows its wave's first
 * member byte, as the scene has always flown it.
 */
export function challengingPath(pattern, offset, screen) {
  const row = CHALLENGE_ROWS[((pattern % CHALLENGING_PATTERN_COUNT) + CHALLENGING_PATTERN_COUNT) % CHALLENGING_PATTERN_COUNT];
  const waves = challengeRowWaves(row);
  const byte = waves[((offset % waves.length) + waves.length) % waves.length].m0;

  const scale = screenScale(screen);
  const state = createEntryFlightState(byte & 0x3f, (byte & 0x40) !== 0 ? 1 : 0);
  const context = {
    playerX: ROM_CANVAS.width / 2,
    stage8Switch: false,
    stage12Switch: false,
    continuousBombing: false,
  };

  const points = compileFlight(state, context, { stopWhen: flewOut });
  return asTrack(points.map((point) => scalePoint(point, scale)));
}

// ----------------------------------------------------------------- returns

/**
 * The re-entry idiom, composed from the ROM's own tokens: F8 (top edge,
 * rawY 0x9C), F9 (over the home column), then FB with the attack tables'
 * `12 00 FF` home tail. This synthetic stream is exactly the sequence the
 * dive tables run after a pass (e.g. red offset 85: `F8 F9 FD -> FB 12 00`);
 * it exists standalone for callers that need a bare "come back in from the
 * top" without a dive attached.
 */
const RETURN_REGION = {
  z80Base: 0,
  bytes: [0xf8, 0xf9, 0xfb, 0x12, 0x00, 0xff, 0xff],
};

/** Re-entry from the top of the screen down into a formation slot. */
export function returnPath(target, screen) {
  const scale = screenScale(screen);
  const romTarget = toRomPoint(target, scale);
  const raw = canvasToRaw(romTarget);
  const state = createFlightState({
    region: RETURN_REGION,
    rawX: raw.rawX,
    rawY: 0x9c,
    angle: 0x300,
  });
  const context = { homeTarget: romTarget, playerX: ROM_CANVAS.width / 2 };

  const points = compileFlight(state, context);
  points.push(romTarget);
  return asTrack(points.map((point) => scalePoint(point, scale)));
}

// ---------------------------------------------------------- captive escape

/**
 * The run a captured fighter makes when its captor dies in formation:
 * "it will swoop down on you... and go away". AUTHORED, in the real segment
 * encoding: the ROM has no path table for this flight (its rogue-fighter
 * path at boss offset 56 covers the formation-kill case Task 5 wires; this
 * is the interim swoop the capture scene already uses). One in-place spin --
 * the `00 rot frames` idiom the bonus paths use -- reads as the ship coming
 * loose, then a straight 4 px/frame run aimed at the player's column, off
 * the bottom, FF.
 */
const CAPTIVE_ESCAPE_REGION = {
  z80Base: 0,
  bytes: [0x00, 0x14, 0x0c, 0x44, 0x00, 0xff, 0xff],
};

/** Total spin the opening segment turns through: rot 0x14 for 12 frames. */
const CAPTIVE_ESCAPE_SPIN = 0x14 * 0x0c;

export function captiveEscapePath(origin, playerX, screen) {
  const scale = screenScale(screen);
  const romOrigin = toRomPoint(origin, scale);
  const raw = canvasToRaw(romOrigin);

  // Aim at the player's column below the screen, computed once at launch --
  // the frozen-vector model every ROM shot uses. The seed pre-compensates
  // for the opening spin so the run leaves on the aimed heading.
  const aimTarget = canvasToRaw({ x: playerX / scale, y: ROM_CANVAS.height + 30 });
  const aim = directionToAngle(aimTarget.rawX - raw.rawX, aimTarget.rawY - raw.rawY);
  const negate = playerX >= origin.x;
  const spin = negate ? -CAPTIVE_ESCAPE_SPIN : CAPTIVE_ESCAPE_SPIN;

  const state = createFlightState({
    region: CAPTIVE_ESCAPE_REGION,
    rawX: raw.rawX,
    rawY: raw.rawY,
    angle: aim - spin,
    negateRotation: negate,
  });

  const points = compileFlight(state, {}, { stopWhen: flewOut });
  return asTrack(points.map((point) => scalePoint(point, scale)));
}
