/**
 * Flight paths.
 *
 * Every path in the game is generated by the bytecode interpreter in
 * `pathcode.js`: a byte program of per-frame heading deltas is compiled into a
 * track, one point per arcade frame, and the sprite walks the track. The
 * cubic Bezier chains this file used to hold are gone; the shapes are now
 * produced by the arcade's own motion model and are approximations only in
 * their authored byte values, not by construction.
 *
 * Structure follows the ROM's two-phase flight: a path block flies the
 * authored shape, and when it runs out the ship steers onto its destination
 * with a clamped turn rate (`compileHoming`). Entry flights home onto their
 * formation slot; dives home onto an exit point aimed at the player.
 */

import {
  asTrack,
  compileHoming,
  compileProgram,
  decodePathProgram,
  PATH_END,
} from './pathcode.js';

export { trackDurationMs } from './pathcode.js';

/**
 * Evaluate a track at t in [0, 1].
 *
 * t maps linearly onto the frame samples, and positions between two samples
 * interpolate linearly -- which is exactly what the arcade shows between two
 * adjacent frames of the interpreter.
 */
export function pointOnPath(track, t) {
  const points = track?.points;
  if (!points || points.length === 0) {
    throw new Error('pointOnPath requires a track with at least one point');
  }
  if (points.length === 1) return { ...points[0] };

  const clamped = Math.min(Math.max(t, 0), 1);
  const scaled = clamped * (points.length - 1);
  const index = Math.min(Math.floor(scaled), points.length - 2);
  const local = scaled - index;
  const a = points[index];
  const b = points[index + 1];

  return { x: a.x + (b.x - a.x) * local, y: a.y + (b.y - a.y) * local };
}

/** Heading along the track at t, in radians, from the surrounding samples. */
export function tangentAngle(track, t) {
  const points = track.points;
  const clamped = Math.min(Math.max(t, 0), 1);
  const scaled = clamped * (points.length - 1);
  const index = Math.min(Math.floor(scaled), points.length - 2);
  const a = points[index];
  const b = points[index + 1];
  return Math.atan2(b.y - a.y, b.x - a.x);
}

/** Exact track length: the sum of its per-frame steps. */
export function pathLength(track) {
  const points = track.points;
  let total = 0;
  for (let i = 1; i < points.length; i += 1) {
    total += Math.hypot(points[i].x - points[i - 1].x, points[i].y - points[i - 1].y);
  }
  return total;
}

/**
 * The lowest fraction of the screen an entry flight may reach.
 *
 * Entry paths must stay clear of the lane the player defends. An earlier
 * revision looped through `height * 0.95`, which put all forty arriving
 * enemies through the player's row and ended the game during the opening
 * stream before a shot could be fired. The test "never descends into the lane
 * the player occupies" pins this against the real `PLAYER.y`.
 */
export const ENTRY_FLOOR_FRACTION = 0.62;

/**
 * How many distinct fly-in shapes exist.
 *
 * The ROM's `PATH_INDEX` holds 24 entries covering 22 unique path blocks, and
 * a caravan's path byte selects one of them in its low six bits. Twenty-two
 * are authored here, matching the arcade's count; bit 6 of the path byte
 * mirrors a shape about the screen's centre line, so the 22 blocks are 44
 * entrances. The byte values are authored -- the published research gives the
 * count and the encoding, not the contents.
 */
export const FLY_IN_PATH_COUNT = 22;

/** Speed a fly-in is flown at, px per interpreter frame (3x the arcade field). */
const ENTRY_SPEED = 8;

/**
 * The 22 fly-in path blocks.
 *
 * Every block is authored as though the enemy enters from the *left* (or the
 * left half of the top edge); the mirror bit reflects the compiled track, so
 * one block serves both sides and a caravan row can put one of each in the
 * air at the same moment. `spawn` is in screen fractions, `heading` in the
 * interpreter's 256-per-circle units (0 up, 64 right, 128 down, 192 left).
 *
 * Grouped loosely: 0-5 are the shapes the first stages fly (0 reproduces the
 * both-sides swoop the stage-1 caravan is sourced to use), 6-13 widen and
 * deepen the sweeps, 14-21 are the busy late-table shapes with double loops
 * and low floors. All 22 bottom out above `ENTRY_FLOOR_FRACTION`;
 * `tests/paths.test.js` pins that for every block on both sides.
 */
const ENTRY_PROGRAMS = [
  // 0 -- the stage-1 swoop: in high, dive across the field, climb out over
  // the top. The shape the sourced first entrance describes.
  { spawn: [-0.06, 0.05], heading: 90, bytes: [0, 30, 2, 40, 4, 32, PATH_END] },
  // 1 -- shallow side sweep with a tight late climb.
  { spawn: [-0.08, 0.3], heading: 80, bytes: [0, 26, 1, 24, 251, 28, PATH_END] },
  // 2 -- high entry, wide dive, small recovering loop.
  { spawn: [-0.09, 0.1], heading: 96, bytes: [0, 16, 1, 36, 5, 30, PATH_END] },
  // 3 -- top entry, straight drop, hard climbing hook.
  { spawn: [0.18, -0.07], heading: 128, bytes: [0, 30, 251, 46, PATH_END] },
  // 4 -- in low along the authored floor, weave, then climb.
  { spawn: [-0.08, 0.44], heading: 72, bytes: [0, 40, 254, 20, 2, 20, 252, 30, PATH_END] },
  // 5 -- long diagonal from the top corner, flattening as it falls.
  { spawn: [0.03, -0.06], heading: 118, bytes: [0, 26, 255, 50, 253, 36, PATH_END] },
  // 6 -- top entry, straight drop, one full tight loop.
  { spawn: [0.1, -0.07], heading: 128, bytes: [0, 24, 250, 43, PATH_END] },
  // 7 -- side entry, banking dive, climb over the far shoulder.
  { spawn: [-0.08, 0.22], heading: 84, bytes: [0, 20, 3, 30, 5, 40, PATH_END] },
  // 8 -- top entry drifting right, sweep to the wall, climb back right.
  { spawn: [0.28, -0.07], heading: 120, bytes: [0, 26, 2, 36, 4, 40, PATH_END] },
  // 9 -- side entry, immediate full loop, then a drift to centre.
  { spawn: [-0.08, 0.18], heading: 96, bytes: [0, 16, 250, 43, 0, 20, PATH_END] },
  // 10 -- the deep sweep: to the floor and around.
  { spawn: [-0.08, 0.26], heading: 88, bytes: [0, 28, 1, 20, 252, 36, PATH_END] },
  // 11 -- top corner cut, one wide circle of the upper field.
  { spawn: [0.12, -0.06], heading: 140, bytes: [0, 20, 253, 78, PATH_END] },
  // 12 -- flat run across mid-field, climb at the far side.
  { spawn: [-0.09, 0.38], heading: 76, bytes: [0, 44, 253, 44, PATH_END] },
  // 13 -- corner dive that crosses its own wake in a half loop.
  { spawn: [0.02, -0.06], heading: 108, bytes: [0, 24, 4, 32, 251, 40, PATH_END] },
  // 14 -- two stacked loops, the slowest-reading shape in the table.
  { spawn: [-0.08, 0.14], heading: 92, bytes: [0, 20, 251, 51, 0, 16, 250, 43, PATH_END] },
  // 15 -- top entry on a long bank, then a climbing counter-turn.
  { spawn: [0.2, -0.07], heading: 132, bytes: [1, 40, 4, 36, PATH_END] },
  // 16 -- side entry that rises first, rolls over, dives, recovers.
  { spawn: [-0.08, 0.34], heading: 52, bytes: [0, 22, 2, 40, 252, 40, PATH_END] },
  // 17 -- broad low hook worked back up through mid-field.
  { spawn: [-0.09, 0.42], heading: 74, bytes: [0, 30, 254, 26, 2, 36, PATH_END] },
  // 18 -- top entry, immediate hard loop, exit toward centre.
  { spawn: [0.14, -0.06], heading: 122, bytes: [0, 14, 250, 43, 0, 18, PATH_END] },
  // 19 -- weave: dive arc, counter arc, climbing hook.
  { spawn: [-0.08, 0.24], heading: 86, bytes: [2, 20, 254, 24, 252, 30, PATH_END] },
  // 20 -- corner dive with a long recovering climb.
  { spawn: [0.1, -0.07], heading: 134, bytes: [0, 26, 254, 22, 253, 42, PATH_END] },
  // 21 -- the busiest: loop, straight run, counter-loop.
  { spawn: [-0.08, 0.1], heading: 98, bytes: [0, 18, 252, 64, 0, 14, 4, 40, PATH_END] },
].map((program) => ({ ...program, steps: decodePathProgram(program.bytes) }));

/**
 * Entry flight from off screen into a formation slot.
 *
 * Compiles the block from its spawn point, reflects the compiled track if the
 * caravan byte's mirror bit asked for it, and then homes onto the slot with a
 * clamped turn rate -- the ROM's own "path block, then tuck into formation".
 * Only the block is reflected: homing runs in world space, so a mirrored
 * flight still delivers its enemy to its real slot.
 */
export function entryPath(variant, target, screen, mirrored = false) {
  const { width, height } = screen;
  const program = ENTRY_PROGRAMS[variant % FLY_IN_PATH_COUNT];

  const { points, state } = compileProgram(
    {
      x: program.spawn[0] * width,
      y: program.spawn[1] * height,
      heading: program.heading,
      speed: ENTRY_SPEED,
    },
    program.steps,
  );

  let approach = points;
  let endState = state;
  if (mirrored) {
    approach = points.map(({ x, y }) => ({ x: width - x, y }));
    endState = { ...state, x: width - state.x, heading: -state.heading };
  }

  const { points: tuck } = compileHoming(endState, target, { maxTurn: 5 });
  return asTrack([...approach, ...tuck.slice(1)]);
}

/** How many dive path blocks the family holds. */
export const DIVE_PROGRAM_COUNT = 8;

/**
 * The dive family: eight peel-and-dive blocks, authored in *relative* space.
 *
 * A dive starts wherever its enemy sits, so the blocks run from (0, 0) with
 * heading 0 (straight up -- a diver lifts out of its slot before rolling
 * over, which is the arcade's own tell). Negative turns roll left; a diver
 * starting on the right half of the screen flies the block mirrored, which is
 * what makes dives sweep outward from whichever side they start on.
 */
const DIVE_PROGRAMS = [
  // 0 -- the basic peel: roll over, straighten into the dive.
  [250, 26, 0, 18, 254, 12, PATH_END],
  // 1 -- full loop before committing.
  [251, 51, 0, 12, PATH_END],
  // 2 -- tight overhead roll into a banked run.
  [251, 32, 3, 20, PATH_END],
  // 3 -- S-dive: roll out left, swing back across, re-centre.
  [250, 22, 253, 24, 3, 16, PATH_END],
  // 4 -- overhead roll into a long shallow diagonal.
  [251, 28, 0, 24, PATH_END],
  // 5 -- roll then zigzag: the hardest to lead.
  [251, 26, 253, 16, 3, 16, 253, 16, PATH_END],
  // 6 -- near-vertical plunge.
  [248, 16, 0, 26, PATH_END],
  // 7 -- corkscrew: over-rotate a full turn, then unwind outward.
  [250, 42, 4, 24, PATH_END],
].map((bytes) => decodePathProgram(bytes));

/**
 * The per-stage flight vectors: which block each type flies, and how hot.
 *
 * The ROM keeps per-stage vectors that select and speed the dive paths; the
 * structure is reproduced here as 26 rows of `[zako, goei, boss, speedTenths]`
 * with authored values. Early rows fly the simple blocks slowly; the plateau
 * rows mix the whole family. Rows clamp at 26, like the difficulty table.
 */
const DIVE_VECTORS = [
  [0, 0, 1, 82], [0, 2, 1, 84], [0, 2, 1, 86], [2, 4, 1, 88],
  [2, 4, 3, 90], [4, 2, 3, 92], [4, 3, 1, 94], [3, 5, 2, 96],
  [0, 4, 7, 98], [2, 5, 7, 100], [4, 3, 1, 100], [3, 6, 2, 102],
  [5, 4, 7, 104], [6, 3, 1, 104], [3, 5, 7, 106], [5, 6, 2, 106],
  [6, 4, 7, 108], [4, 5, 1, 108], [5, 3, 7, 110], [6, 5, 2, 110],
  [3, 6, 7, 110], [5, 4, 1, 110], [6, 5, 7, 110], [4, 6, 2, 110],
  [5, 6, 7, 110], [6, 5, 7, 110],
];

const DIVE_TYPE_COLUMN = { zako: 0, goei: 1, boss: 2 };

/** Which dive block a type flies at a stage row, and its speed, px/frame. */
export function diveVectorFor(enemyType = 'zako', stageIndex = 0) {
  const row = DIVE_VECTORS[Math.min(Math.max(stageIndex, 0), DIVE_VECTORS.length - 1)];
  const column = DIVE_TYPE_COLUMN[enemyType] ?? 0;
  return { program: row[column], speed: row[3] / 10 };
}

/**
 * Dive run: peel out of formation, fly the block, then home onto an exit
 * point below the screen aimed at where the player was when the dive
 * launched. Aiming at launch rather than tracking is the arcade's model: the
 * flight vector is committed, and dodging it is the player's game.
 */
export function divePath(origin, playerX, screen, { enemyType = 'zako', stageIndex = 0 } = {}) {
  const { width, height } = screen;
  const mirrored = origin.x >= width / 2;
  const { program, speed } = diveVectorFor(enemyType, stageIndex);

  const { points, state } = compileProgram(
    { x: 0, y: 0, heading: 0, speed },
    DIVE_PROGRAMS[program % DIVE_PROGRAM_COUNT],
  );

  const sign = mirrored ? -1 : 1;
  const world = points.map(({ x, y }) => ({ x: origin.x + sign * x, y: origin.y + y }));
  const endState = {
    x: origin.x + sign * state.x,
    y: origin.y + state.y,
    heading: mirrored ? -state.heading : state.heading,
    speed,
  };

  const { points: run } = compileHoming(
    endState,
    { x: playerX, y: height + 80 },
    { maxTurn: 4, maxFrames: 300 },
  );

  return asTrack([...world, ...run.slice(1)]);
}

/**
 * How many distinct Challenging Stage routes exist.
 *
 * The arcade has eight, and because they land on stages 3, 7, 11 ... the last
 * of them is not seen until stage 31. Cycling fewer than eight is the single
 * most common shortcut in a Galaga clone and it shows: the bonus round starts
 * repeating itself less than halfway through a good run.
 */
export const CHALLENGING_PATTERN_COUNT = 8;

/** Speed a bonus-round flight is flown at, px per interpreter frame. */
const CHALLENGING_SPEED = 8.5;

/**
 * The eight Challenging Stage blocks.
 *
 * Unlike an entry block these never terminate on a slot: they enter off
 * screen, trace their shape, and are authored to *exit* off screen, so there
 * is no homing phase at all -- the whole route is the program. `laneShift`
 * spreads a wave across the field by moving the spawn point per member;
 * `mirrorByOffset` flies odd members reflected, which is how two streams
 * cross.
 */
const CHALLENGING_PROGRAMS = [
  // 0 -- crossing streams: a long diagonal to mid-field, then a climbing
  // turn out through the far side. Odd members fly it mirrored, which is
  // what makes the two streams cross at the centre.
  { spawn: [-0.07, -0.05], heading: 106, laneShift: 0, mirrorByOffset: true,
    bytes: [0, 60, 254, 30, 0, 50, PATH_END] },
  // 1 -- vertical loop: down the lane, a loop and a half, out the top.
  { spawn: [0.2, -0.06], heading: 128, laneShift: 0.12, mirrorByOffset: false,
    bytes: [0, 44, 252, 96, 0, 50, PATH_END] },
  // 2 -- wide arc sweeping the field, hooking up and out the far side.
  { spawn: [-0.07, 0.1], heading: 84, laneShift: 0, mirrorByOffset: true,
    bytes: [0, 50, 2, 30, 4, 40, 0, 60, PATH_END] },
  // 3 -- figure hook through the middle band, out the way it came.
  { spawn: [-0.07, 0.3], heading: 76, laneShift: 0, mirrorByOffset: true,
    bytes: [0, 40, 4, 45, 252, 23, 0, 30, PATH_END] },
  // 4 -- descending zigzag, three switchbacks widening as they fall.
  { spawn: [0.3, -0.06], heading: 150, laneShift: 0.1, mirrorByOffset: false,
    bytes: [251, 22, 5, 24, 251, 24, 5, 22, 254, 40, 0, 40, PATH_END] },
  // 5 -- twin columns: down with a weave, then a hard fan outward.
  { spawn: [0.16, -0.06], heading: 128, laneShift: 0.12, mirrorByOffset: false,
    bytes: [2, 18, 252, 18, 2, 18, 254, 30, 0, 60, PATH_END] },
  // 6 -- orbit: in along the middle, one circle of the field, climb away.
  { spawn: [-0.07, 0.34], heading: 76, laneShift: 0, mirrorByOffset: true,
    bytes: [0, 20, 253, 86, 254, 20, 0, 70, PATH_END] },
  // 7 -- shallow S across the upper band, the flattest of the eight.
  { spawn: [-0.07, 0.16], heading: 72, laneShift: 0, mirrorByOffset: true,
    bytes: [0, 30, 2, 26, 252, 26, 0, 55, PATH_END] },
].map((program) => ({ ...program, steps: decodePathProgram(program.bytes) }));

/**
 * Challenging Stage fly-through. `pattern` selects one of the eight blocks,
 * `offset` is the member's place in its wave: it shifts the spawn lane and,
 * on crossing patterns, mirrors odd members so the streams interleave.
 */
export function challengingPath(pattern, offset, screen) {
  const { width, height } = screen;
  const program = CHALLENGING_PROGRAMS[pattern % CHALLENGING_PATTERN_COUNT];
  const lane = program.laneShift * (offset % 5);
  const mirrored = program.mirrorByOffset && offset % 2 === 1;

  const { points } = compileProgram(
    {
      x: (program.spawn[0] + lane) * width,
      y: program.spawn[1] * height,
      heading: program.heading,
      speed: CHALLENGING_SPEED,
    },
    program.steps,
  );

  if (!mirrored) return asTrack(points);
  return asTrack(points.map(({ x, y }) => ({ x: width - x, y })));
}

/** The escape block: bank away from the player before committing. */
const CAPTIVE_ESCAPE_PROGRAM = decodePathProgram([3, 16, 254, 18, PATH_END]);

/**
 * The run a captured fighter makes when its captor dies in formation.
 *
 * Shooting the boss while it sits in the grid does not hand the ship back. The
 * freed captive "will swoop down on you... it will disappear off the bottom of
 * the screen and go away": one last attack run, aimed at the player, and then
 * it is gone for the rest of the game. The block banks away first -- the ship
 * coming loose -- and the homing phase swoops it down the player's own column.
 */
export function captiveEscapePath(origin, playerX, screen) {
  const { height, width } = screen;
  const away = playerX >= origin.x ? -1 : 1;

  const { points, state } = compileProgram(
    { x: 0, y: 0, heading: 128, speed: 7 },
    CAPTIVE_ESCAPE_PROGRAM,
  );

  const sign = away;
  const world = points.map(({ x, y }) => ({ x: origin.x + sign * x, y: origin.y + y }));
  const endState = {
    x: origin.x + sign * state.x,
    y: origin.y + state.y,
    heading: sign === 1 ? state.heading : -state.heading,
    speed: 7,
  };
  void width;

  const { points: swoop } = compileHoming(
    endState,
    { x: playerX, y: height + 80 },
    { maxTurn: 6, maxFrames: 300 },
  );

  return asTrack([...world, ...swoop.slice(1)]);
}

/** Re-entry from the top of the screen back into a formation slot. */
export function returnPath(target, screen) {
  const { width } = screen;
  const fromLeft = target.x < width / 2;
  const entryX = fromLeft ? width * 0.25 : width * 0.75;

  const { points, state } = compileProgram(
    { x: entryX, y: -60, heading: 128, speed: 7 },
    decodePathProgram([0, 10, PATH_END]),
  );

  const { points: drop } = compileHoming(state, target, { maxTurn: 5 });
  return asTrack([...points, ...drop.slice(1)]);
}
