/**
 * The play scene.
 *
 * This file orchestrates. Every rule it needs, where the formation sits, what a
 * kill is worth, whether this stage is a Challenging Stage, what the capture
 * machine allows next, lives in a pure module under `src/systems` and is unit
 * tested there. What remains here is Phaser: sprites, input, timers, and
 * collision callbacks.
 *
 * That split is deliberate. The version this replaced was a single 867-line
 * class where the same concerns were interleaved, which is how it grew four
 * independent booleans to track one capture sequence and could represent
 * states that should not exist.
 */

import {
  CAPTURE,
  DIVE,
  DUAL_FIGHTER_OFFSET_X,
  FORMATION,
  FORMATION_BOTTOM_Y,
  LIFE_ICONS_SHOWN,
  PLAYER,
  SCREEN,
  SHIP_ART,
  SHIP_DRAWN_PX,
  SPRITE_SCALE,
  CHALLENGING,
  TRANSFORM,
} from '../config.js';
import {
  EnemyType,
  buildFormationSlots,
  buildEntryGroups,
  breathScaleAt,
  swayOffsetAt,
  slotWorldPosition,
  clampFormationCentre,
  FORMATION_SIZE,
} from '../systems/formation.js';
import {
  entryPath,
  divePath,
  returnPath,
  challengingPath,
  captiveEscapePath,
} from '../systems/paths.js';
import {
  createFlight,
  advanceFlight,
  isFlightComplete,
  flightProgress,
  flightTransform,
} from '../systems/flight.js';
import {
  advanceNoFire,
  advanceScheduler,
  createAttackScheduler,
  createNoFireState,
} from '../systems/attack.js';
import { DIP_DEFAULTS, bonusSchemeFor, loadDips } from '../systems/dips.js';
import {
  STARFIELD_SCROLL,
  advanceStarfield,
  createStarfield,
  setStarfieldScroll,
  visibleStars,
} from '../systems/starfield.js';
import {
  scoreFor,
  extraLivesEarned,
  PERFECT_BONUS,
  CAPTURED_FIGHTER_POINTS,
  transformKillPoints,
  TRANSFORM_SET_SIZE,
  CHALLENGING_STAGE_HIT_POINTS,
} from '../systems/scoring.js';
import {
  isChallengingStage,
  stageDifficulty,
  stageFlags,
  enemiesFireDuringEntry,
  enemiesBomb,
  captureAllowed,
  challengingPatternIndex,
  challengingRoster,
  transformTypeFor,
  caravanFor,
  RANK_NAMES,
  nextStage,
} from '../systems/stages.js';
import {
  createSession,
  activePlayer,
  withActive,
  loseShip,
  playerLabel,
} from '../systems/players.js';
import { demoInput, DEMO_DURATION_MS } from '../systems/demo.js';
import {
  CaptureState,
  CaptureEvent,
  RescueOutcome,
  transition,
  resolveCaptorDestroyed,
  isBeamDangerous,
  hasDualFighter,
  bulletLimit,
  captiveCanBomb,
} from '../systems/capture.js';
import { resolveStorage, loadScoreTable, loadRank } from '../systems/persistence.js';
import {
  createFlagTextures,
  createShipTextures,
  createTransformTextures,
  flagTextureKey,
  shipTextureKey,
  FLAG_DRAWN_WIDTH,
} from '../art/textures.js';
import { applyShipArt, queueLocalArt } from '../art/localArt.js';
import { installSoundBank } from '../audio/soundBank.js';
import { queueLocalAudio } from '../audio/localAudio.js';
import { recordShot, recordHit } from '../systems/stats.js';
import {
  SOUND_NAMES,
  challengeResultSound,
  deathSoundFor,
  playerShotSound,
} from '../systems/audio.js';
import {
  EnemyMode,
  createEnemy,
  isDiving,
  canBeginDive,
  settleIntoFormation,
  showBossDamage,
  createTransformEnemy,
} from '../entities/enemy.js';

export class GameScene extends Phaser.Scene {
  constructor() {
    super({ key: 'GameScene' });
  }

  preload() {
    // Only the projectiles and the two effects are loaded. Every ship in the
    // game is generated from the pixel grids in `src/art` (see
    // `createShipTextures`), and the starfield is generated by
    // `src/systems/starfield.js` rather than drawn.
    this.load.image('bullet', 'assets/images/player_laser.png');
    this.load.image('laser', 'assets/images/enemy_laser.png');
    this.load.image('explosion', 'assets/images/explosion.png');
    this.load.image('tractorBeam', 'assets/images/tractor_beam.png');

    // A local checkout may keep its own ship artwork; see `src/art/localArt.js`.
    // Absent, this is one 404 and the drawn ships are used.
    queueLocalArt(this);

    // The same arrangement for audio, and the only thing loaded for it. Every
    // sound is synthesised in `create`; this probe is the one way the cabinet's
    // own samples can get in, and only on a machine that already has them.
    queueLocalAudio(this);
  }

  /**
   * How this game was started.
   *
   * Three things arrive from outside: how many players pressed start, whether
   * this is the attract screen playing itself, and the operator's difficulty
   * rank. All three have defaults, so `scene.start('GameScene')` with nothing
   * at all is a one-player game at the factory rank -- which is what the
   * results screen's "play again" does.
   */
  init(data) {
    this.demo = data?.demo === true;
    this.storage = resolveStorage(globalThis.localStorage);
    // The demo is not a game the operator's settings apply to: it is the
    // machine showing what the game looks like, and it should look like the one
    // a new player would get.
    this.rank = this.demo ? 0 : loadRank(this.storage);

    // The operator's switch block decides how many fighters a credit buys
    // and which bonus scheme pays. A demo plays the factory machine.
    this.dips = this.demo ? { ...DIP_DEFAULTS } : loadDips(this.storage);
    this.bonusScheme = bonusSchemeFor(this.dips);

    this.session = createSession({
      playerCount: this.demo ? 1 : (data?.playerCount ?? 1),
      startingLives: this.dips.lives,
    });

    // The no-fire bug, if the operator has switched it on. Once triggered it
    // holds until the "machine" is power cycled -- the registry survives
    // scene restarts, so only a page reload clears it, which is the bug's
    // real cure.
    this.noFire = {
      ...createNoFireState(),
      triggered: this.registry.get('noFireTriggered') === true,
    };
  }

  create() {
    // The live copies of the active player's game. They are held here rather
    // than read out of the session every frame because they change many times a
    // second; `bankTurn` folds them back when the turn ends.
    this.loadTurn();
    // The number in the HUD is the top of the board, not a second high score
    // kept beside it. A cabinet whose header disagreed with its own BEST 5
    // would be showing one of the two wrong.
    this.highScore = loadScoreTable(this.storage)[0].score;
    this.captureState = CaptureState.IDLE;
    this.shotIndex = 0;

    this.isGameOver = false;
    this.isInvulnerable = false;
    this.stageResolving = false;
    this.formationElapsed = 0;
    this.challengingHits = 0;
    this.currentBreath = 1;
    this.currentSway = 0;

    // Generated rather than loaded: every ship in the game is pixel art
    // authored in `src/art`, so the textures are built once here, before
    // anything asks for one.
    createShipTextures(this);
    createTransformTextures(this);

    this.createWorld();
    this.createPlayer();
    this.createGroups();
    this.createHud();
    this.createInput();
    this.registerCollisions();

    // Brief grace on the opening spawn so the arriving wave cannot land a hit
    // before the player has had a chance to move.
    this.makeInvulnerable(PLAYER.invulnerableMs);

    if (this.demo) this.beginDemo();

    // A two-player game says whose turn it is before the first wave, the way
    // the cabinet does. A one-player game does not, because there is nobody to
    // distinguish it from.
    if (this.session.playerCount > 1) {
      this.showBanner(playerLabel(this.session.active), 1500);
      this.time.delayedCall(1500, () => {
        if (!this.isGameOver) this.beginStage(this.stage);
      });
      return;
    }

    this.beginStage(this.stage);
  }

  // ------------------------------------------------------------------ turns

  /**
   * Load the active player's game into the live fields.
   *
   * Two-player Galaga is alternating, so everything the machine tracks it
   * tracks twice and swaps the pair over at a handover. This is that swap in
   * one direction; `bankTurn` is the other.
   */
  loadTurn() {
    const player = activePlayer(this.session);

    // Which player the live fields below belong to. It is not always the
    // session's active player: `loseShip` hands the machine over at the instant
    // a ship is destroyed, but the outgoing player's ship is still exploding
    // and their score is still in `this.score` for another second and a half.
    // Without this the HUD spent that second showing the dying player's score
    // in the incoming player's column.
    this.turnOwner = player.index;

    this.score = player.score;
    this.lives = player.lives;
    this.stage = player.stage;
    // Stages *played*, which is not the same as the stage number once the
    // counter has rolled over past 255. Difficulty is driven from this so a
    // player who gets that far is not handed the opening round back.
    this.round = player.round;
    this.stats = player.stats;
  }

  /** Fold the live fields back into the active player's record. */
  bankTurn() {
    this.session = withActive(this.session, {
      score: this.score,
      lives: this.lives,
      stage: this.stage,
      round: this.round,
      stats: this.stats,
    });
  }

  /**
   * Hand the machine to the other player.
   *
   * Everything on the board belongs to the outgoing player, so all of it goes:
   * the formation, whatever was diving, any beam, and any capture in progress.
   * The incoming player restarts their *own* stage from its opening wave, which
   * is what the arcade does -- a turn is a stage attempt, and the stage the
   * other player was half way through is none of their business.
   */
  handOverTurn() {
    this.clearTimers();
    this.stageAdvanceTimer?.remove();
    this.stageAdvanceTimer = null;
    // Held until `beginStage` clears it. Without it the empty board left by the
    // teardown below reads as a cleared stage, and the incoming player is
    // credited with finishing the stage the outgoing one died on.
    this.stageResolving = true;

    this.enemies.clear(true, true);
    this.enemyBullets.clear(true, true);
    this.bullets.clear(true, true);
    this.clearCaptive();
    this.clearDualFighter();
    this.clearBeam();
    this.captor = null;
    this.captureState = CaptureState.IDLE;
    this.sfx.enemyDive.stop();

    this.loadTurn();
    this.refreshHud();

    this.player.enableBody(true, SCREEN.width / 2, PLAYER.y, true, true);
    this.player.setAngle(0);
    this.makeInvulnerable(PLAYER.invulnerableMs);

    this.showBanner(playerLabel(this.session.active), 1600);
    this.time.delayedCall(1600, () => {
      if (this.isGameOver) return;
      this.beginStage(this.stage);
    });
  }

  // ------------------------------------------------------------------ setup

  createWorld() {
    // The 63-star hardware field. It streams during play and stops dead
    // while no fighter is on the board, which is the cabinet's own tell that
    // the world has paused; see `updateStarfield`.
    this.starfield = setStarfieldScroll(createStarfield(), STARFIELD_SCROLL.game);
    this.starLayer = this.add.graphics().setScrollFactor(0);

    // Synthesised into the audio cache here, in `create`, rather than fetched
    // in `preload`: nothing is downloaded, and by now the loader has finished,
    // so anything a local checkout supplied is already in the cache and is
    // left where it is. See `src/audio/soundBank.js`.
    installSoundBank(this);

    this.sfx = Object.fromEntries(SOUND_NAMES.map((key) => [key, this.sound.add(key)]));

    // Galaga plays a low pulse under the whole board. It is the thing that
    // makes a cleared screen feel quiet, so it runs for as long as the scene
    // does rather than being started and stopped per stage.
    // Stopped by key first: replaying the scene builds a second Sound object,
    // and two copies of a loop is a drone rather than a pulse.
    this.sound.stopByKey('ambient');
    this.sfx.ambient.play({ volume: 0.18, loop: true });
  }

  createPlayer() {
    this.player = this.physics.add
      .sprite(SCREEN.width / 2, PLAYER.y, shipTextureKey('player'))
      .setCollideWorldBounds(true);
    applyShipArt(this.player, 'player');

    // The same 62% body every enemy gets. The fighter is drawn as a narrow
    // hull inside a 48px frame, and a body filling that frame would have the
    // player shot down by bombs passing through empty space beside the wings.
    this.player.body.setSize(this.player.width * 0.62, this.player.height * 0.62, true);
    this.player.body.setAllowGravity(false);
    this.dualFighter = null;
  }

  createGroups() {
    this.enemies = this.physics.add.group();
    this.bullets = this.physics.add.group();
    this.enemyBullets = this.physics.add.group();

    // The dual fighter lives in a group of its own so its collisions can be
    // registered once here, rather than wired up and torn down every time one
    // is earned and lost.
    this.wingman = this.physics.add.group();

    // A held captive is a target. Shooting your own fighter is a legal, scored
    // move in the arcade, so the captive needs a body and an overlap of its
    // own rather than being a decorative image riding on its captor.
    this.captives = this.physics.add.group();
  }

  /**
   * The cabinet's own header: 1UP over one running score on the left, HIGH
   * SCORE over the board's best in the middle, 2UP over the other on the right.
   *
   * The blink is not decoration -- it marks whose turn is live. Which is why
   * only the column belonging to the player currently flying blinks, and why in
   * a one-player game the 2UP column is drawn dim and empty: that is exactly
   * what a two-player cabinet looks like when one person is playing, and it is
   * what gives the blink on the left something to mean.
   */
  createHud() {
    const heading = { font: '15px monospace', fill: '#ff4444' };
    const value = { font: '18px monospace', fill: '#ffffff' };
    const idle = '#663333';

    this.playerHeadings = [
      this.add.text(20, 12, '1UP', heading).setDepth(20),
      this.add
        .text(SCREEN.width - 20, 12, '2UP', heading)
        .setOrigin(1, 0)
        .setDepth(20),
    ];

    this.add
      .text(SCREEN.width / 2, 12, 'HIGH SCORE', heading)
      .setOrigin(0.5, 0)
      .setDepth(20);

    this.playerScores = [
      this.add.text(20, 32, '', value).setDepth(20),
      this.add
        .text(SCREEN.width - 20, 32, '', value)
        .setOrigin(1, 0)
        .setDepth(20),
    ];

    // One blink tween per column, both created up front and paused: a handover
    // moves the blink by pausing one and resuming the other, so the tweens are
    // never rebuilt and the two can never end up blinking together.
    this.playerBlinks = this.playerHeadings.map((text) =>
      this.tweens.add({
        targets: text,
        alpha: 0.15,
        duration: 500,
        yoyo: true,
        repeat: -1,
        paused: true,
      }),
    );

    if (this.session.playerCount < 2) {
      this.playerHeadings[1].setColor(idle);
      this.playerScores[1].setColor('#555555');
    }

    // The rank the operator left the machine on. Drawn small and out of the
    // way, because on a real cabinet it is not on the screen at all -- it is a
    // switch inside the box -- but a browser has no box, and a player who has
    // set it to D deserves to be told why the first screen is shooting at them.
    if (this.rank > 0) {
      this.add
        .text(SCREEN.width / 2, 54, `RANK ${RANK_NAMES[this.rank]}`, {
          font: '12px monospace',
          fill: '#886644',
        })
        .setOrigin(0.5, 0)
        .setDepth(20);
    }

    // Which column is currently blinking, so that `refreshHud` -- which runs on
    // every point scored -- can leave a running tween alone instead of
    // restarting it several times a second.
    this.blinkingColumn = -1;
    this.highScoreText = this.add
      .text(SCREEN.width / 2, 32, '', { ...value, fill: '#ffcc00' })
      .setOrigin(0.5, 0)
      .setDepth(20);

    this.bannerText = this.add
      .text(SCREEN.width / 2, SCREEN.height / 2, '', {
        font: '30px monospace',
        fill: '#ffffff',
        align: 'center',
      })
      .setOrigin(0.5)
      .setDepth(30)
      .setVisible(false);

    this.lifeIcons = [];
    this.flagIcons = [];
    createFlagTextures(this);
    this.refreshHud();
  }

  createInput() {
    this.keys = this.input.keyboard.addKeys({
      left: 'A',
      right: 'D',
      altLeft: 'LEFT',
      altRight: 'RIGHT',
    });

    // During a demo the controls belong to the machine, and the only thing a
    // key does is what it does on a cabinet mid-attract: start a real game.
    if (this.demo) {
      this.input.keyboard.once('keydown-SPACE', () => this.startRealGame(1));
      this.input.keyboard.once('keydown-ONE', () => this.startRealGame(1));
      this.input.keyboard.once('keydown-TWO', () => this.startRealGame(2));
      return;
    }

    // Movement is a held state and is read per frame; firing is an event.
    // Polling `JustDown` for the trigger loses any press that begins and ends
    // inside one frame, and tapping faster than the refresh rate is exactly
    // what a two-shot limit teaches a player to do. The `repeat` guard is what
    // stops a held key turning into the operating system's key-repeat rate.
    this.input.keyboard.on('keydown-SPACE', (event) => {
      if (!event.repeat) this.fire();
    });
  }

  // ------------------------------------------------------------------- demo

  /**
   * Put the machine in charge of the fighter.
   *
   * The demo is a real game of Galaga in every respect except who is holding
   * the stick: the same stages, the same formation, the same capture, the same
   * scoring. What changes is that `updatePlayer` reads `demoInput` instead of
   * the keyboard, that the screen says so, and that nothing about it is ever
   * written to the score table -- a machine that put its own demo on the board
   * would be filling the board with itself.
   */
  beginDemo() {
    // Well clear of the row the fighter flies in: the machine's own ship spends
    // the whole demo travelling along the bottom of the screen, and text behind
    // it is text nobody can read.
    this.demoLabel = this.add
      .text(SCREEN.width / 2, SCREEN.height * 0.72, 'DEMO PLAY', {
        font: '20px monospace',
        fill: '#ffcc00',
      })
      .setOrigin(0.5)
      .setDepth(30);

    this.tweens.add({
      targets: this.demoLabel,
      alpha: 0.25,
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    this.add
      .text(SCREEN.width / 2, SCREEN.height * 0.72 + 28, 'PUSH START BUTTON   1P: SPACE   2P: 2', {
        font: '14px monospace',
        fill: '#8899bb',
      })
      .setOrigin(0.5)
      .setDepth(30);

    this.demoTimer = this.time.delayedCall(DEMO_DURATION_MS, () => this.endDemo());
  }

  /** Hand the screen back to the attract loop. */
  endDemo() {
    if (!this.demo) return;
    this.demo = false;
    this.isGameOver = true;
    this.clearTimers();
    this.sound.stopAll();
    this.scene.start('TitleScene');
  }

  /** Someone pressed start while the machine was playing: give them the game. */
  startRealGame(playerCount) {
    if (!this.demo) return;
    this.demo = false;
    this.isGameOver = true;
    this.demoTimer?.remove();
    this.clearTimers();
    this.sound.stopAll();
    this.sound.play('coin', { volume: 0.5 });
    this.scene.start('GameScene', { playerCount });
  }

  /**
   * The board as the demo pilot sees it.
   *
   * Deliberately narrow: positions and nothing else. The pilot is a pure
   * function of this, which is what lets `tests/demo.test.js` fly it without a
   * canvas, and it is why the pilot cannot cheat by reading a timer or a
   * random seed the player has no access to.
   */
  demoBoard() {
    return {
      playerX: this.player.x,
      playerY: this.player.y,
      screenWidth: SCREEN.width,
      margin: SHIP_DRAWN_PX / 2,
      bombs: this.enemyBullets
        .getChildren()
        .filter((bullet) => bullet.active)
        .map((bullet) => ({ x: bullet.x, y: bullet.y })),
      targets: this.enemies
        .getChildren()
        .filter((enemy) => enemy.active)
        .map((enemy) => ({ x: enemy.x, y: enemy.y })),
      beam:
        this.beam && isBeamDangerous(this.captureState)
          ? { x: this.beam.x, width: CAPTURE.beamWidth }
          : null,
    };
  }

  registerCollisions() {
    this.physics.add.overlap(this.bullets, this.enemies, (bullet, enemy) => {
      bullet.destroy();
      this.onEnemyHit(enemy);
    });

    this.physics.add.overlap(this.player, this.enemies, (_player, enemy) => {
      // Challenging Stage enemies fly through without attacking, exactly as
      // they do in the arcade. Their pass crosses the player's lane, so this
      // guard is what keeps the bonus round a bonus.
      if (this.challenging) return;
      if (!this.canBeHurt() || !enemy.active) return;
      this.destroyEnemy(enemy, false);
      this.onPlayerHit();
    });

    this.physics.add.overlap(this.player, this.enemyBullets, (_player, bullet) => {
      if (!this.canBeHurt() || !bullet.active) return;
      bullet.destroy();
      this.onPlayerHit();
    });

    // The second ship is as solid as the first, which is what the doubled
    // firepower is paid for.
    this.physics.add.overlap(this.wingman, this.enemies, (_wingman, enemy) => {
      if (this.challenging) return;
      if (!this.canBeHurt() || !enemy.active) return;
      this.destroyEnemy(enemy, false);
      this.onPlayerHit();
    });

    // Shooting your own captured fighter. Worth 1,000 and loses the ship for
    // good -- the player gives up any chance of the dual fighter to take the
    // points, which is the trade the arcade offers and the reason the captive
    // is left hanging there in the formation rather than being untouchable.
    this.physics.add.overlap(this.bullets, this.captives, (bullet, captive) => {
      if (!bullet.active || !captive.active) return;
      bullet.destroy();
      this.onCaptiveShot();
    });

    this.physics.add.overlap(this.wingman, this.enemyBullets, (_wingman, bullet) => {
      if (!this.canBeHurt() || !bullet.active) return;
      bullet.destroy();
      this.onPlayerHit();
    });

    // A captive that has broken loose is flying at the player and can ram
    // them, exactly as a diving enemy can. While it is still pinned under its
    // captor it is only a target, so the guard is on the escape flight rather
    // than on the sprite existing.
    for (const ship of [this.player, this.wingman]) {
      this.physics.add.overlap(ship, this.captives, (_ship, captive) => {
        if (!captive.flight || !this.canBeHurt() || !captive.active) return;
        this.clearCaptive();
        this.onPlayerHit();
      });
    }
  }

  // ----------------------------------------------------------------- stages

  beginStage(stage) {
    // Cancel any stage advance still pending, so two stages can never be
    // started from one clear.
    this.stageAdvanceTimer?.remove();
    this.stageAdvanceTimer = null;

    this.stageResolving = false;
    this.formationElapsed = 0;
    this.challengingHits = 0;
    this.difficulty = stageDifficulty(this.round, this.rank);
    this.challenging = isChallengingStage(stage);
    this.transformType = transformTypeFor(stage);

    // The stage's attack scheduler: per-type launch counters out of the
    // difficulty row. It starts counting when the wave finishes assembling.
    this.attack = createAttackScheduler(this.difficulty);
    this.attackActive = false;

    // A docked dual fighter carries over into the next stage; anything else
    // mid-sequence does not. Clearing the state but leaving the second ship on
    // screen would have left it firing two shots against a two-shot limit and
    // no longer able to absorb a hit.
    if (!hasDualFighter(this.captureState)) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      this.clearDualFighter();
    }

    this.captor = null;
    this.clearCaptive();
    this.clearBeam();
    this.clearTimers();

    this.showBanner(this.challenging ? 'CHALLENGING STAGE' : `STAGE ${stage}`, 1800);
    this.sfx[this.challenging ? 'challengeStart' : 'stageFlag'].play({ volume: 0.5 });
    this.refreshHud();

    this.time.delayedCall(1800, () => {
      if (this.isGameOver) return;
      if (this.challenging) {
        this.launchChallengingStage();
      } else {
        this.launchFormation();
      }
    });
  }

  /**
   * Bring the wave on as five flights of eight, in this stage's entrance
   * pattern.
   *
   * The pattern is a property of the stage, not of the flight: all five
   * flights of a wave belong to one of the arcade's three entrances, which is
   * what makes an entrance recognisable rather than a shuffle. Within it, each
   * member carries the curve it flies and its step in the launch order, so the
   * both-sides pattern can put two arrivals in the air at once while the other
   * two stay single file.
   *
   * All forty sprites are created up front, parked at their curve's off-screen
   * start, and only their flights are staggered. That matters: the stage is
   * considered clear when no enemy is left alive, so an enemy waiting to
   * launch has to already exist.
   */
  launchFormation() {
    // Round 1 holds fire through the whole assembly; from round 2 the arriving
    // wave bombs on its way in.
    const entryFire = enemiesFireDuringEntry(this.stage);
    const slots = buildFormationSlots();
    // The caravan is a property of the stage *and* the operator's rank, which
    // is the arcade's own `d_combat_stg_dat_idx[rank * 17 + row]`. Every member
    // carries the shape it flies, whether that shape is mirrored, and the beat
    // it launches on, all decoded out of the row's path bytes.
    const groups = buildEntryGroups(caravanFor(this.stage, this.rank));

    groups.forEach((group) => {
      const groupDelay = group.index * FORMATION.groupIntervalMs;

      group.members.forEach(({ slotIndex, pathVariant, mirrored, step }) => {
        const slot = slots[slotIndex];
        const start = entryPath(pathVariant, this.slotPosition(slot), SCREEN, mirrored).points[0];
        const enemy = createEnemy(this, this.enemies, slot, start);
        // An arriving ship gets at most one shot on the way in, and only from
        // stage 2: the entry-fire flag is off on the opening row at every rank.
        enemy.bombsLeft = entryFire && !this.noFire.triggered && Math.random() < 0.25 ? 1 : 0;
        enemy.bombCooldownMs = 0;

        this.time.delayedCall(groupDelay + step * FORMATION.entryStaggerMs, () => {
          if (!enemy.active) return;
          // Built at launch, not at spawn: the last flight sets off ten
          // seconds after the first, by which time the formation has breathed
          // and swayed away from where its slots were.
          enemy.flight = createFlight(
            entryPath(pathVariant, this.slotPosition(slot), SCREEN, mirrored),
            FORMATION.entryDurationMs,
          );
        });
      });
    });

    this.scheduleCaptureAttempts();

    // The arcade lets the wave finish arriving before anything attacks, so the
    // entry choreography is never cut across by a dive.
    this.assemblyTimer = this.time.delayedCall(this.assemblyDurationMs(groups), () => {
      this.assemblyTimer = null;
      if (this.isGameOver || this.stageResolving) return;
      // The arcade lets the wave finish arriving before anything attacks;
      // from here the per-type launch counters run.
      this.attackActive = true;
    });
  }

  /**
   * How long the whole wave takes, from the first launch to the last dock.
   *
   * Read off the last member's step rather than assumed to be eight, because a
   * both-sides flight launches its eight in four paired steps and is home
   * sooner. Taking the maximum keeps the "nothing attacks until everyone has
   * landed" rule true for every pattern.
   */
  assemblyDurationMs(groups) {
    const lastStep = Math.max(
      ...groups.flatMap((group) => group.members.map((member) => member.step)),
    );

    return (
      (groups.length - 1) * FORMATION.groupIntervalMs +
      lastStep * FORMATION.entryStaggerMs +
      FORMATION.entryDurationMs
    );
  }

  /**
   * Challenging Stage: forty enemies fly through and never fire or dive.
   * Clearing all of them pays the perfect bonus.
   *
   * Structured like the entry wave, as five flights of eight rather than one
   * forty-ship stream. Everyone in a flight shares one route and one lane, so
   * the eight arrive nose to tail and can be swept with a single held line of
   * fire; the lane changes between flights so the pattern is traced out across
   * the field instead of being redrawn in the same place five times.
   */
  launchChallengingStage() {
    const pattern = challengingPatternIndex(this.stage) ?? 0;
    // A bonus round is not the attack formation flying a different route: it is
    // one rank of enemy plus four Boss Galaga. The slots are still the
    // formation's, because they are what splits forty ships into five flights
    // of eight, but who sits in them comes from `challengingRoster`.
    const roster = challengingRoster(this.stage) ?? [];
    const slots = buildFormationSlots().map((slot, index) => ({
      ...slot,
      type: roster[index] ?? slot.type,
    }));

    buildEntryGroups().forEach((group) => {
      const groupDelay = group.index * CHALLENGING.groupIntervalMs;
      // One offset for the whole flight: same curve, same lane, single file.
      const path = challengingPath(pattern, group.index, SCREEN);

      group.slotIndices.forEach((slotIndex, position) => {
        const enemy = createEnemy(this, this.enemies, slots[slotIndex], path[0][0]);
        enemy.mode = EnemyMode.PASSING;

        this.time.delayedCall(groupDelay + position * CHALLENGING.staggerMs, () => {
          if (!enemy.active) return;
          enemy.flight = createFlight(path, CHALLENGING.passDurationMs);
        });
      });
    });
  }

  completeStage() {
    if (this.stageResolving) return;
    this.stageResolving = true;
    this.clearTimers();

    if (this.challenging) {
      const perfect = this.challengingHits === FORMATION_SIZE;
      this.sfx.challengeClear.play({ volume: 0.5 });
      this.sfx[challengeResultSound(this.challengingHits, FORMATION_SIZE)].play({ volume: 0.6 });

      // The cabinet's own wording. A round that fell short reports the total
      // already paid at 100 a hit rather than paying it again here; only the
      // perfect bonus is awarded at the end, because only it is a bonus.
      if (perfect) {
        this.addScore(PERFECT_BONUS);
        this.showBanner(`PERFECT!!\nSPECIAL BONUS ${PERFECT_BONUS} PTS`, 2200);
      } else {
        const paid = this.challengingHits * CHALLENGING_STAGE_HIT_POINTS;
        this.showBanner(`NUMBER OF HITS ${this.challengingHits}\nBONUS ${paid} PTS`, 2200);
      }
    }

    this.stageAdvanceTimer = this.time.delayedCall(this.challenging ? 2400 : 1200, () => {
      this.stageAdvanceTimer = null;
      if (this.isGameOver) return;
      this.round += 1;
      this.stage = nextStage(this.stage);
      this.beginStage(this.stage);
    });
  }

  // ---------------------------------------------------------------- attacks

  /**
   * Pump the per-type launch counters.
   *
   * Called every frame once the wave has assembled. The scheduler decides
   * which types launch this frame against the row's active-bomber ceiling,
   * and whether this frame's Zako launch is instead the transform pull --
   * the arcade's schedule-driven trigger, in place of the 15-second timer an
   * earlier revision ran.
   */
  updateAttacks(delta) {
    if (!this.attackActive || this.challenging || this.stageResolving) return;

    // The no-fire lock-up accrues while the last enemies are being dodged
    // rather than shot; see `advanceNoFire` for the conditions.
    if (this.dips.noFireBug && !this.noFire.triggered) {
      this.noFire = advanceNoFire(this.noFire, delta, {
        enabled: true,
        enemiesRemaining: this.enemies.countActive(true),
      });
      if (this.noFire.triggered) this.registry.set('noFireTriggered', true);
    }

    if (!this.captureIsIdle()) return;

    const activeBombers = this.enemies.getChildren().filter(isDiving).length;
    const availableTypes = [
      ...new Set(this.enemies.getChildren().filter(canBeginDive).map((e) => e.enemyType)),
    ];

    const { state, launches, transformPull } = advanceScheduler(this.attack, delta, {
      activeBombers,
      availableTypes,
      transformStage: Boolean(this.transformType),
    });
    this.attack = state;

    launches.forEach((type) => this.launchDive(type));
    if (transformPull) this.triggerTransform();
  }

  scheduleCaptureAttempts() {
    this.captureTimer = this.time.addEvent({
      delay: CAPTURE.attemptIntervalMs,
      loop: true,
      callback: () => this.attemptCapture(),
    });
  }

  /**
   * Pull a Zako out of the grid, pulsate it, and replace it with a bonus trio.
   *
   * Only a Zako is eligible, which is what the arcade does and also what keeps
   * the formation's shape readable: the Goei rows and the boss row stay intact
   * while the bottom of the grid thins out.
   */
  triggerTransform() {
    if (this.isGameOver || this.challenging || !this.transformType) return;
    if (!this.captureIsIdle()) return;

    const eligible = this.enemies
      .getChildren()
      .filter((enemy) => enemy.enemyType === EnemyType.ZAKO && canBeginDive(enemy));
    if (eligible.length === 0) return;

    const chosen = Phaser.Utils.Array.GetRandom(eligible);
    chosen.transforming = true;

    // The pulse is the player's warning. The tween is what decides when the
    // swap happens, so a transform can never fire on a frame where the Zako
    // has already been shot: `onComplete` re-checks that it is still alive.
    this.tweens.add({
      targets: chosen,
      // The ship textures are drawn at scale 1, so the warning pulse is a
      // straight 35% swell rather than a multiple of an authoring scale.
      scale: 1.35,
      duration: TRANSFORM.pulseDurationMs,
      yoyo: true,
      repeat: TRANSFORM.pulseRepeats,
      onComplete: () => {
        if (!chosen.active || this.isGameOver || this.stageResolving) return;
        const origin = { x: chosen.x, y: chosen.y };
        this.destroyEnemy(chosen, false);
        this.spawnTransformSet(origin);
      },
    });
  }

  /**
   * Three bonus ships abreast, each flying its own attack run from where the
   * Zako was standing.
   *
   * They share one `set` object by reference; see `createTransformEnemy`. They
   * are ordinary members of the enemy group, so every collider that already
   * exists applies to them, and they leave off the bottom of the screen on
   * their own if the player does not take them.
   */
  spawnTransformSet(origin) {
    this.sfx.transformSet.play({ volume: 0.5 });
    const set = { type: this.transformType, remaining: TRANSFORM_SET_SIZE };

    for (let i = 0; i < TRANSFORM_SET_SIZE; i += 1) {
      const start = {
        x: origin.x + (i - (TRANSFORM_SET_SIZE - 1) / 2) * TRANSFORM.spacingX,
        y: origin.y,
      };
      const enemy = createTransformEnemy(this, this.enemies, this.transformType, start, set);
      enemy.bombsLeft = this.enemiesArmed() ? this.difficulty.continuousBombs : 0;
      enemy.bombCooldownMs = 0;
      enemy.flight = createFlight(
        divePath(start, this.player.x, SCREEN, { stageIndex: this.round }),
        TRANSFORM.runDurationMs,
      );
    }
  }

  /**
   * True when no beam or capture animation is occupying the board.
   *
   * HELD counts as free. A ship can be held above its captor for the rest of
   * the stage, and treating that as busy would stop every dive until the
   * player shot the captor down.
   */
  captureIsIdle() {
    return (
      this.captureState === CaptureState.IDLE ||
      this.captureState === CaptureState.DUAL ||
      this.captureState === CaptureState.HELD
    );
  }

  /**
   * Launch one attacker of the type whose counter just expired.
   *
   * The pick within the type is random; the *type* is the scheduler's, which
   * is the arcade's split of the decision.
   */
  launchDive(type) {
    if (this.isGameOver || this.challenging || !this.captureIsIdle()) return;

    const eligible = this.enemies.getChildren().filter(canBeginDive);
    const ofType = eligible.filter((enemy) => enemy.enemyType === type);
    if (ofType.length === 0) return;

    // A boss holding a captured fighter has to actually leave formation for
    // the rescue to be possible at all, so it is weighted to lead the dive
    // rather than waiting for a one-in-four draw.
    const captorLeads =
      type === EnemyType.BOSS &&
      this.captor?.captiveAttached === true &&
      canBeginDive(this.captor) &&
      Math.random() < CAPTURE.captorDiveChance;

    const leader = captorLeads ? this.captor : Phaser.Utils.Array.GetRandom(ofType);
    const attackers = [leader];

    // A Boss Galaga clones Goei wingmen onto its run -- the clone-attack
    // count is a difficulty-table parameter -- which is what makes it worth
    // up to 1600 rather than 400.
    if (leader.enemyType === EnemyType.BOSS && this.difficulty.cloneAttackCount > 0) {
      const escorts = eligible
        .filter((enemy) => enemy !== leader && enemy.enemyType === EnemyType.GOEI)
        .slice(0, this.difficulty.cloneAttackCount);
      attackers.push(...escorts);
    }

    leader.escortCount = attackers.length - 1;
    attackers.forEach((enemy, index) => {
      this.time.delayedCall(index * 140, () => this.beginDive(enemy));
    });
  }

  beginDive(enemy) {
    if (!canBeginDive(enemy)) return;
    this.beginDiveSound();
    enemy.mode = EnemyMode.DIVING;

    // A captor takes the fighter it is holding down with it, and the fighter
    // fights: rearm it for this run. See `updateCaptive` for the release.
    if (enemy.captiveAttached && this.captive) this.captive.hasBombed = false;

    // The continuous-bomb allowance is a difficulty-table parameter: how many
    // bombs one attacker may string together on a run, released from the aim
    // band rather than at a fixed point. Stage 1 is unarmed in the arcade --
    // the opening row's bomb-drop flags are zero at the factory rank -- so
    // the only way to lose a ship on the first screen is to be flown into.
    enemy.bombsLeft = this.enemiesArmed() ? this.difficulty.continuousBombs : 0;
    enemy.bombCooldownMs = 0;
    // Which block the dive flies and how hot comes from the per-stage flight
    // vectors, the arcade's own per-type selection.
    enemy.flight = createFlight(
      divePath({ x: enemy.x, y: enemy.y }, this.player.x, SCREEN, {
        enemyType: enemy.enemyType,
        stageIndex: this.round,
      }),
      DIVE.durationMs / this.difficulty.diveSpeed,
    );
  }

  /**
   * Whether this stage's attackers carry bombs at all.
   *
   * The stage's own flag, and then the no-fire lock-up on top of it: once
   * that has tripped, nothing shoots again until the page is reloaded.
   */
  enemiesArmed() {
    return enemiesBomb(this.stage, this.rank) && !this.noFire.triggered;
  }

  attemptCapture() {
    if (this.isGameOver || this.challenging || !this.captureIsIdle()) return;
    if (!this.player.active) return;
    // Two gates the arcade applies and a clock cannot: the stage has to allow
    // captures at all, and there has to be enough formation left for hunting
    // the captor down to be a plan the player can act on.
    if (!captureAllowed(this.stage, this.enemies.countActive(true), this.rank)) return;

    const bosses = this.enemies
      .getChildren()
      .filter((enemy) => enemy.enemyType === EnemyType.BOSS && canBeginDive(enemy));
    if (bosses.length === 0) return;

    const boss = Phaser.Utils.Array.GetRandom(bosses);
    this.captureState = transition(this.captureState, CaptureEvent.DEPLOY_BEAM);
    if (this.captureState !== CaptureState.BEAM_OPENING) return;

    boss.mode = EnemyMode.DIVING;
    this.captor = boss;
    this.sfx.bossEntrance.play({ volume: 0.5 });

    // Down into the player's half of the field and across toward the player's
    // column, then open the beam. The descent is the tell: it is a markedly
    // different move from the one-loop dive every other attacker makes, and it
    // is the player's warning to get out of the way.
    //
    // The sideways travel is capped, so the boss aims once on the way down
    // rather than tracking. A player who reads the descent and moves can still
    // slip out from under it.
    this.tweens.add({
      targets: boss,
      x: this.aimedBeamX(boss),
      y: CAPTURE.descendToY,
      duration: CAPTURE.descendDurationMs,
      ease: 'Sine.easeInOut',
      onComplete: () => this.openBeam(boss),
    });
  }

  /**
   * Where a descending boss lines its beam up: the player's column, as far as
   * it can reach, and never so far out that the beam hangs off the screen.
   */
  aimedBeamX(boss) {
    const reach = Phaser.Math.Clamp(
      this.player.x - boss.x,
      -CAPTURE.aimTravelPx,
      CAPTURE.aimTravelPx,
    );
    const half = CAPTURE.beamWidth / 2;
    return Phaser.Math.Clamp(boss.x + reach, half, SCREEN.width - half);
  }

  openBeam(boss) {
    if (!boss.active || this.isGameOver) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      return;
    }

    this.sfx.beamOpen.play({ volume: 0.5 });
    this.beam = this.add
      .image(boss.x, boss.y + CAPTURE.beamOffsetY, 'tractorBeam')
      .setOrigin(0.5, 0)
      .setDisplaySize(CAPTURE.beamWidth * 1.4, CAPTURE.beamLength)
      .setAlpha(0)
      .setDepth(5);

    this.tweens.add({
      targets: this.beam,
      alpha: 0.85,
      duration: CAPTURE.beamOpenMs,
      onComplete: () => {
        if (this.captureState === CaptureState.BEAM_OPENING) {
          this.captureState = CaptureState.BEAM_ACTIVE;
        }
      },
    });

    this.time.delayedCall(CAPTURE.beamOpenMs + CAPTURE.beamHoldMs, () => this.closeBeam());
  }

  closeBeam() {
    if (!isBeamDangerous(this.captureState)) return;
    this.captureState = transition(this.captureState, CaptureEvent.BEAM_TIMEOUT);
    this.clearBeam();

    const boss = this.captor;
    this.captor = null;
    this.sendCaptorHome(boss);
  }

  clearBeam() {
    if (this.beam) {
      this.beam.destroy();
      this.beam = null;
    }
  }

  /**
   * Fly a boss back to its slot from wherever it stopped.
   *
   * A boss that has deployed a beam is halted low on the field, so it climbs
   * back from there. Handing it `returnPath`, the way a finished diver is
   * handled, would snap it off the top of the screen first, because that path
   * starts above the ceiling.
   */
  sendCaptorHome(boss) {
    if (!boss || !boss.active) return;

    const target = this.slotPosition(boss.slot);
    boss.mode = EnemyMode.RETURNING;

    this.tweens.add({
      targets: boss,
      x: target.x,
      y: target.y,
      duration: DIVE.returnDurationMs,
      ease: 'Sine.easeInOut',
      onComplete: () => settleIntoFormation(boss, this.slotPosition(boss.slot)),
    });
  }

  capturePlayer() {
    this.captureState = transition(this.captureState, CaptureEvent.PLAYER_CAUGHT);
    if (this.captureState !== CaptureState.CAPTURING) return;

    this.sfx.beamCapture.play({ volume: 0.6 });
    this.player.disableBody(true, false);
    this.clearBeam();

    // A dual fighter caught in a beam loses its second ship rather than
    // carrying it up to the boss.
    this.clearDualFighter();

    const boss = this.captor;
    this.tweens.add({
      targets: this.player,
      x: boss ? boss.x : this.player.x,
      y: boss ? boss.y + CAPTURE.captiveOffsetY : 0,
      angle: 360,
      duration: CAPTURE.captureRiseMs,
      onComplete: () => this.onCaptureComplete(),
    });
  }

  onCaptureComplete() {
    this.player.setVisible(false);
    this.player.setAngle(0);
    this.captureState = transition(this.captureState, CaptureEvent.CAPTURE_COMPLETE);
    this.sfx.captured.play({ volume: 0.6 });
    this.showBanner('FIGHTER CAPTURED', 1400);

    const boss = this.captor;
    if (boss && boss.active) {
      this.captive = this.captives
        .create(boss.x, boss.y + CAPTURE.captiveOffsetY, shipTextureKey('captive'))
        .setDepth(6);
      applyShipArt(this.captive, 'captive');
      this.captive.body.setAllowGravity(false);
      boss.captiveAttached = true;

      // The captor rejoins the formation with its prize in tow, so the player
      // can hunt it down. `this.captor` stays set: the held ship is drawn
      // against it every frame from here until one of them is destroyed.
      this.sendCaptorHome(boss);
    }

    this.loseLife();
  }

  /**
   * Fly the held fighter: pinned beneath its captor, or, once it has broken
   * loose, along its own last attack run.
   *
   * A captured Fighter is not a trophy hanging in the grid. It has joined the
   * enemy side, and on the one run where its captor brings it down within
   * reach it fires on the player alongside it. The release point is the same
   * fraction of the run the captor's own bomb uses, so the two shots arrive
   * together and the captor's dive reads as the double threat it is.
   */
  updateCaptive(delta) {
    const captive = this.captive;
    if (!captive) return;

    if (captive.flight) {
      this.advanceCaptiveEscape(captive, delta);
      return;
    }

    if (!this.captor || !this.captor.active) return;
    captive.setPosition(this.captor.x, this.captor.y + CAPTURE.captiveOffsetY);

    const readyToBomb =
      captiveCanBomb(this.captureState, isDiving(this.captor)) &&
      !captive.hasBombed &&
      this.captor.flight &&
      flightProgress(this.captor.flight) >= DIVE.bombAtProgress;

    if (readyToBomb) {
      captive.hasBombed = true;
      this.fireEnemyBullet(captive);
    }
  }

  /**
   * The swoop a captive makes after its captor dies in formation.
   *
   * It gets one shot on the way past, which is what makes taking the wrong
   * shot at a captor cost something rather than merely forfeiting the rescue,
   * and then it leaves through the bottom of the screen for good.
   */
  advanceCaptiveEscape(captive, delta) {
    captive.flight = advanceFlight(captive.flight, delta);
    const { x, y, angle } = flightTransform(captive.flight);
    captive.setPosition(x, y);
    captive.setRotation(angle);

    if (!captive.hasBombed && flightProgress(captive.flight) >= DIVE.bombAtProgress) {
      captive.hasBombed = true;
      this.fireEnemyBullet(captive);
    }

    if (isFlightComplete(captive.flight)) this.clearCaptive();
  }

  clearCaptive() {
    if (this.captive) {
      this.captive.destroy();
      this.captive = null;
    }
  }

  clearDualFighter() {
    if (this.dualFighter) {
      this.dualFighter.destroy();
      this.dualFighter = null;
    }
  }

  rescueCaptive() {
    this.captureState = transition(this.captureState, CaptureEvent.CAPTOR_DESTROYED);
    if (this.captureState !== CaptureState.RETURNING) return;

    if (!this.captive) {
      this.captureState = transition(this.captureState, CaptureEvent.DOCK_COMPLETE);
      return;
    }

    this.tweens.add({
      targets: this.captive,
      x: this.player.x + DUAL_FIGHTER_OFFSET_X,
      y: this.player.y,
      duration: CAPTURE.dockDurationMs,
      ease: 'Sine.easeInOut',
      onComplete: () => this.dockCaptive(),
    });
  }

  dockCaptive() {
    this.clearCaptive();
    this.captureState = transition(this.captureState, CaptureEvent.DOCK_COMPLETE);

    // The rescued ship can be a second or so in the air, and the player can be
    // killed by something else while it is. That death resets the machine, so
    // the dock no longer lands in DUAL and there is nothing to dock onto:
    // building the sprite anyway left a wingman flying beside a dead player
    // that fired nothing and absorbed nothing.
    if (!hasDualFighter(this.captureState)) return;

    // Created in the wingman group so it carries a body of its own. Twice the
    // firepower for twice the width to be hit across is the whole trade; an
    // image with no body would have made the upgrade free.
    this.dualFighter = this.wingman
      .create(this.player.x + DUAL_FIGHTER_OFFSET_X, this.player.y, shipTextureKey('player'))
      .setDepth(4);
    applyShipArt(this.dualFighter, 'player');
    this.dualFighter.body.setSize(
      this.dualFighter.width * 0.62,
      this.dualFighter.height * 0.62,
      true,
    );
    this.dualFighter.body.setAllowGravity(false);
    this.dualFighter.body.setImmovable(true);

    this.sfx.rescued.play({ volume: 0.6 });
    this.showBanner('DUAL FIGHTER', 1200);
  }

  // ----------------------------------------------------------------- combat

  onEnemyHit(enemy) {
    if (!enemy.active) return;

    this.stats = recordHit(this.stats);

    // A transform bonus ship pays for itself and, on the third kill, for the
    // set. `transformKillPoints` takes the count still alive including this
    // one, so the scene never has to know which kill completes a trio.
    if (enemy.transformSet) {
      const set = enemy.transformSet;
      const points = transformKillPoints(set.type, set.remaining);
      set.remaining -= 1;
      this.destroyEnemy(enemy, true);

      this.addScore(points);
      // Only the set bonus is worth interrupting the screen for; 160 on its own
      // is an ordinary kill and belongs in the score, not in a banner.
      if (set.remaining === 0) this.showBanner(String(points), 1100);
      return;
    }

    if (this.challenging) {
      this.challengingHits += 1;
      this.addScore(scoreFor(enemy.enemyType, { challenging: true }));
      this.destroyEnemy(enemy, true);
      return;
    }

    enemy.health -= 1;

    // A Boss Galaga survives its first hit and changes colour to show it.
    if (enemy.health > 0) {
      showBossDamage(enemy);
      this.sfx[deathSoundFor(enemy.enemyType, { destroyed: false })].play({ volume: 0.4 });
      return;
    }

    this.addScore(
      scoreFor(enemy.enemyType, {
        diving: isDiving(enemy),
        escorts: enemy.escortCount ?? 0,
      }),
    );

    // Galaga's rescue rule: the ship only comes back if its captor is shot
    // down on a dive. Read the mode before the sprite is destroyed, and let
    // the pure rule decide, so "diving or not" is the only thing the scene
    // contributes.
    const outcome =
      enemy.captiveAttached === true
        ? resolveCaptorDestroyed(this.captureState, isDiving(enemy))
        : RescueOutcome.NONE;

    this.destroyEnemy(enemy, true);

    if (outcome === RescueOutcome.RESCUED) {
      this.addScore(CAPTURED_FIGHTER_POINTS);
      this.rescueCaptive();
    } else if (outcome === RescueOutcome.CAPTIVE_LOST) {
      this.loseCaptive();
    }
  }

  /**
   * The player shot their own captured fighter.
   *
   * Counts as a hit, pays 1,000, and ends the capture: the captor is unflagged
   * so that killing it later cannot rescue a ship that no longer exists, and
   * the state machine is driven to IDLE through the same `CAPTIVE_DESTROYED`
   * transition the "captor died in formation" path uses.
   */
  onCaptiveShot() {
    if (!this.captive) return;

    this.stats = recordHit(this.stats);

    // The 1,000 is for shooting your *own* fighter -- a ship you could still
    // have won back. Once the captive has broken loose and is diving at the
    // player the capture is already resolved and the ship is gone either way,
    // so shooting it down is just self-defence and pays nothing.
    if (!this.captive.flight) {
      this.addScore(CAPTURED_FIGHTER_POINTS);
      this.showBanner(String(CAPTURED_FIGHTER_POINTS), 1100);
      if (this.captor) this.captor.captiveAttached = false;
      this.captureState = transition(this.captureState, CaptureEvent.CAPTIVE_DESTROYED);
    }

    const burst = this.add
      .sprite(this.captive.x, this.captive.y, 'explosion')
      .setScale(SPRITE_SCALE.explosion);
    this.time.delayedCall(220, () => burst.destroy());
    this.sfx.explosion.play({ volume: 0.4 });

    this.clearCaptive();
  }

  /**
   * The captor died in formation, so the ship it was holding turns on the
   * player.
   *
   * The arcade does not simply delete it: the freed captive "will swoop down
   * on you... it will disappear off the bottom of the screen and go away". So
   * it flies one last attack run, with a shot in it, and only then is gone.
   * That run is the cost of taking the wrong shot at a captor; an earlier
   * revision tweened it straight down off the screen, which made shooting a
   * captor in formation free apart from the forfeited rescue.
   */
  loseCaptive() {
    this.captureState = transition(this.captureState, CaptureEvent.CAPTIVE_DESTROYED);
    if (!this.captive) return;

    this.showBanner('FIGHTER LOST', 1400);
    this.captive.hasBombed = false;
    this.captive.flight = createFlight(
      captiveEscapePath({ x: this.captive.x, y: this.captive.y }, this.player.x, SCREEN),
      CAPTURE.captiveEscapeMs,
    );
  }

  destroyEnemy(enemy, withExplosion) {
    if (withExplosion) {
      const burst = this.add
        .sprite(enemy.x, enemy.y, 'explosion')
        .setScale(
          enemy.enemyType === EnemyType.BOSS
            ? SPRITE_SCALE.bossExplosion
            : SPRITE_SCALE.explosion,
        );
      this.time.delayedCall(220, () => burst.destroy());
      // Each rank of enemy has its own cry in the arcade, which is how a
      // player knows what they hit without looking away from their own ship.
      this.sfx[deathSoundFor(enemy.enemyType)].play({ volume: 0.4 });
    }

    if (enemy === this.captor) {
      this.captor = null;
      this.clearBeam();
    }

    enemy.destroy();
  }

  onPlayerHit() {
    // The dual fighter absorbs a hit by reverting to a single ship.
    if (hasDualFighter(this.captureState)) {
      this.captureState = transition(this.captureState, CaptureEvent.DUAL_HIT);
      this.clearDualFighter();
      this.makeInvulnerable(1000);
      return;
    }

    this.sfx.playerDeath.play({ volume: 0.5 });
    const burst = this.add
      .sprite(this.player.x, this.player.y, 'explosion')
      .setScale(SPRITE_SCALE.playerExplosion);
    this.time.delayedCall(320, () => burst.destroy());

    this.player.disableBody(true, false);
    this.player.setVisible(false);
    this.loseLife();
  }

  /**
   * The active player lost a ship.
   *
   * In a one-player game this is what it always was: spend a life, respawn, or
   * end the game. In a two-player game it is also the moment the machine
   * changes hands, so the whole decision is deferred to `loseShip` in
   * `players.js` and this reads the answer off it. The three outcomes are
   * different sentences on the screen -- another ship, `GAME OVER PLAYER 1`
   * while player two carries on, or the results screen -- and nothing here
   * decides which; it only draws them.
   */
  loseLife() {
    // Read before the session moves on: this is the player who just died, and
    // by the time `loseShip` has returned, the machine may already belong to
    // somebody else.
    const flyer = this.session.active;

    this.bankTurn();
    const outcome = loseShip(this.session);
    this.session = outcome.session;
    this.lives = Math.max(this.lives - 1, 0);
    this.refreshHud();

    if (outcome.over) {
      this.endGame();
      return;
    }

    // One player is finished but the other is not. Say so, because otherwise
    // the handover looks like an ordinary change of turn and the player who is
    // out never learns that they are.
    if (outcome.retired) {
      this.showBanner(`GAME OVER\n${playerLabel(flyer)}`, 1800);
    }

    this.time.delayedCall(PLAYER.respawnDelayMs, () => {
      if (this.isGameOver) return;
      if (outcome.handedOver) {
        this.handOverTurn();
        return;
      }
      this.respawnPlayer();
    });
  }

  respawnPlayer() {
    // A ship taken before this death is still held above its captor, and the
    // machine has to stay in HELD for shooting that captor down to rescue it.
    // Resetting here unconditionally is what made the dual fighter, and with
    // it the whole point of the capture, unreachable: the held ship was left
    // stranded on screen with no state left that could bring it back.
    if (this.captureState !== CaptureState.HELD) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      // The reset drops DUAL, so the second ship goes with it. Leaving the
      // sprite behind would have flown a wingman that no longer doubled the
      // bullet limit and no longer absorbed a hit.
      this.clearDualFighter();
    }
    this.clearBeam();

    this.player.enableBody(true, SCREEN.width / 2, PLAYER.y, true, true);
    this.player.setAngle(0);
    this.makeInvulnerable(PLAYER.invulnerableMs);
  }

  makeInvulnerable(durationMs) {
    this.isInvulnerable = true;
    this.tweens.add({
      targets: this.player,
      alpha: 0.25,
      yoyo: true,
      repeat: Math.max(Math.floor(durationMs / 200) - 1, 0),
      duration: 100,
      onComplete: () => {
        this.player.setAlpha(1);
        this.isInvulnerable = false;
      },
    });
  }

  canBeHurt() {
    return this.player.active && !this.isInvulnerable && !this.isGameOver;
  }

  endGame() {
    this.bankTurn();
    this.isGameOver = true;
    this.clearTimers();
    // The board goes quiet before the results screen speaks. The attack-run
    // loop is stopped by hand because `updateDiveSound` no longer runs once the
    // game is over, and a held loop would play under the whole results screen.
    this.sfx.ambient.stop();
    this.sfx.enemyDive.stop();

    // The machine's own game does not get a results screen and never touches
    // the board: an attract loop that could write to the high-score table would
    // eventually fill it with itself.
    if (this.demo) {
      this.demoTimer?.remove();
      this.time.delayedCall(1600, () => this.endDemo());
      return;
    }

    this.time.delayedCall(1200, () => {
      // The score is banked by the results screen, not here: it is the screen
      // that asks for initials, and a run that made the board has to be written
      // once, with the name attached, rather than saved twice. The pause is
      // what it always was -- bullets already in the air still land during it,
      // and banking early left the results screen showing a score above its own
      // high score.
      this.scene.start('GameOverScene', {
        session: this.session,
        // A run played after the no-fire lock-up was against a machine that
        // could not shoot back; its score does not rank.
        scoreDisqualified: this.noFire.triggered,
      });
    });
  }

  // ----------------------------------------------------------------- update

  update(_time, delta) {
    if (this.isGameOver) return;

    this.updateStarfield(delta);
    this.formationElapsed += delta;

    this.updateFormation(delta);
    this.updateAttacks(delta);
    this.updateDiveSound();
    this.updatePlayer();
    this.updateCaptive(delta);
    this.updateBeam(delta);
    this.cullProjectiles();
    this.checkStageComplete();
  }

  /**
   * Stream the sky, or stop it.
   *
   * The hardware field stops scrolling while no fighter is on the board --
   * between a death and the respawn -- and that stop is the most legible
   * "the world is holding its breath" cue the cabinet has.
   */
  updateStarfield(delta) {
    const speed = this.player.active ? STARFIELD_SCROLL.game : 0;
    if (this.starfield.rowsPerFrame !== speed) {
      this.starfield = setStarfieldScroll(this.starfield, speed);
    }

    this.starfield = advanceStarfield(this.starfield, delta);
    this.starLayer.clear();
    for (const star of visibleStars(this.starfield, SCREEN)) {
      this.starLayer.fillStyle(star.color, 1);
      this.starLayer.fillRect(star.x, star.y, 2, 2);
    }
  }

  updateFormation(delta) {
    this.currentBreath = breathScaleAt(this.formationElapsed, {
      periodMs: FORMATION.breathPeriodMs,
      amplitude: FORMATION.breathAmplitude,
    });
    this.currentSway = swayOffsetAt(this.formationElapsed, {
      periodMs: FORMATION.swayPeriodMs,
      amplitude: FORMATION.swayAmplitude,
    });

    this.enemies.getChildren().forEach((enemy) => {
      if (!enemy.active) return;

      if (enemy.flight) {
        this.advanceEnemyFlight(enemy, delta);
        return;
      }

      if (enemy.mode === EnemyMode.IN_FORMATION) {
        const position = this.slotPosition(enemy.slot);
        enemy.setPosition(position.x, position.y);
      }
    });
  }

  advanceEnemyFlight(enemy, delta) {
    enemy.flight = advanceFlight(enemy.flight, delta);
    const { x, y, angle } = flightTransform(enemy.flight);
    enemy.setPosition(x, y);
    enemy.setRotation(angle);

    // Bombs release from the aim band: when the attacker is above the player
    // and roughly in their column, up to its continuous-bomb allowance, with
    // a reload between shots. That is the arcade's model -- a diver that
    // crosses the player's column twice shoots twice -- and it is why moving
    // under a dive is a decision rather than a free dodge.
    //
    // A transform bonus ship flies `PASSING` because it never joins a
    // formation, but it is making an attack run, not a fly-past: the trio is
    // the highest-value target on the board and an unarmed one would be a free
    // 1,480 points. Challenging-stage enemies are `PASSING` too and are the
    // genuinely harmless case; they never have bombs to spend.
    const bombing =
      enemy.mode === EnemyMode.DIVING ||
      enemy.mode === EnemyMode.ENTERING ||
      enemy.transformSet !== undefined;
    if (bombing && enemy.bombsLeft > 0) {
      enemy.bombCooldownMs = Math.max((enemy.bombCooldownMs ?? 0) - delta, 0);
      const inBand =
        Math.abs(enemy.x - this.player.x) < DIVE.bombAimWindowPx &&
        enemy.y > FORMATION_BOTTOM_Y - 40 &&
        enemy.y < PLAYER.y - 140;
      if (inBand && enemy.bombCooldownMs === 0 && this.player.active) {
        enemy.bombsLeft -= 1;
        enemy.bombCooldownMs = DIVE.bombReloadMs;
        this.fireEnemyBullet(enemy);
      }
    }

    if (!isFlightComplete(enemy.flight)) return;

    switch (enemy.mode) {
      case EnemyMode.ENTERING:
      case EnemyMode.RETURNING:
        settleIntoFormation(enemy, this.slotPosition(enemy.slot));
        break;

      case EnemyMode.DIVING:
        // Flew off the bottom; come back in from the top.
        enemy.mode = EnemyMode.RETURNING;
        enemy.flight = createFlight(
          returnPath(this.slotPosition(enemy.slot), SCREEN),
          DIVE.returnDurationMs,
        );
        break;

      case EnemyMode.PASSING:
        // Challenging-stage enemies leave for good.
        enemy.destroy();
        break;

      default:
        enemy.flight = null;
    }
  }

  /**
   * The attack-run sound, held for as long as anything is attacking.
   *
   * In the arcade this runs for the duration of a dive rather than being a
   * one-shot at the moment of launch, which is what makes a screen with four
   * attackers in the air sound different from one with a single Zako on its
   * way down. Started when the first attacker leaves the grid and stopped by
   * `updateFormation` once the sky is clear again, so overlapping dives share
   * one voice instead of stacking a copy per diver.
   */
  beginDiveSound() {
    if (this.sfx.enemyDive.isPlaying) return;
    this.sfx.enemyDive.play({ volume: 0.25, loop: true });
  }

  /** Stop the attack-run loop once nothing is flying at the player. */
  updateDiveSound() {
    if (!this.sfx.enemyDive.isPlaying) return;
    const attacking = this.enemies.getChildren().some((enemy) => enemy.active && isDiving(enemy));
    if (!attacking) this.sfx.enemyDive.stop();
  }

  fireEnemyBullet(enemy) {
    if (this.enemyBullets.countActive(true) >= DIVE.maxBombs) return;

    const bullet = this.enemyBullets
      .create(enemy.x, enemy.y + 18, 'laser')
      .setScale(SPRITE_SCALE.laser);
    bullet.body.setAllowGravity(false);

    this.sfx.enemyFire.play({ volume: 0.2 });
    const angle = Math.atan2(this.player.y - enemy.y, this.player.x - enemy.x);
    bullet.setVelocity(Math.cos(angle) * DIVE.bombSpeed, Math.sin(angle) * DIVE.bombSpeed);
  }

  updatePlayer() {
    if (!this.player.active) return;

    // In a demo the stick is held by `demoInput`, which is a pure function of
    // the board and lives in `src/systems/demo.js`. It drives the same fields a
    // player's keys drive, so nothing downstream of here knows the difference --
    // the demo is subject to the two-shot limit, the beam and everything else.
    const held = this.demo
      ? demoInput(this.demoBoard())
      : {
          left: this.keys.left.isDown || this.keys.altLeft.isDown,
          right: this.keys.right.isDown || this.keys.altRight.isDown,
          fire: false,
        };

    const { left, right } = held;
    if (held.fire) this.fire();
    this.player.setVelocityX(((right ? 1 : 0) - (left ? 1 : 0)) * PLAYER.speed);

    // World bounds stop the *body*, which is deliberately narrower than the
    // frame the ship is drawn in, so on its own it would let the wingtips slide
    // off the edge of the screen. Clamping the sprite keeps the whole fighter
    // visible without widening the hitbox back out.
    // A docked wingman is part of the ship the player is flying, so the pair is
    // clamped together rather than letting the second ship leave the field.
    const halfShip = SHIP_DRAWN_PX / 2;
    const rightLimit =
      SCREEN.width - halfShip - (this.dualFighter ? DUAL_FIGHTER_OFFSET_X : 0);
    this.player.x = Phaser.Math.Clamp(this.player.x, halfShip, rightLimit);

    if (this.dualFighter) {
      this.dualFighter.setPosition(this.player.x + DUAL_FIGHTER_OFFSET_X, this.player.y);
    }
  }

  /**
   * Galaga's two-bullet limit, doubled while the dual fighter is docked. It is
   * the central constraint of the game: it makes the hit-miss ratio meaningful
   * and stops the player from holding down fire.
   *
   * The limit is the *only* gate. There is deliberately no rate-of-fire timer:
   * in the arcade a shot that connects frees its slot immediately, so accurate
   * close-range play is rewarded with a faster gun. A flat cooldown, which an
   * earlier revision had at 180ms, severs that link and is what makes most
   * clones feel sluggish. What stops the player holding down fire is that each
   * miss occupies a slot until it flies off the top of the screen.
   */
  fire() {
    // Fired from a key event rather than from `update`, so this has to check
    // for itself that there is a ship to fire from: a dead player between
    // respawns, or a game already over, would otherwise still shoot.
    if (this.isGameOver || !this.player.active) return;
    if (this.bullets.countActive(true) >= bulletLimit(this.captureState)) return;

    this.spawnBullet(this.player.x);
    let shots = 1;

    if (this.dualFighter) {
      this.spawnBullet(this.dualFighter.x);
      shots = 2;
    }

    this.stats = recordShot(this.stats, shots);
    this.sfx[playerShotSound(this.shotIndex)].play({ volume: 0.3 });
    this.shotIndex += 1;
  }

  spawnBullet(x) {
    const bullet = this.bullets
      .create(x, this.player.y - 26, 'bullet')
      .setScale(SPRITE_SCALE.bullet);
    bullet.body.setAllowGravity(false);
    bullet.setVelocityY(-PLAYER.bulletSpeed);
  }

  updateBeam(delta) {
    if (!this.beam || !this.captor || !this.captor.active) return;

    this.beam.setPosition(this.captor.x, this.captor.y + CAPTURE.beamOffsetY);
    if (!isBeamDangerous(this.captureState) || !this.canBeHurt()) return;

    // Inside the beam column: drag the player toward its centre, and capture
    // once they have been pulled far enough up it.
    const withinX = Math.abs(this.player.x - this.beam.x) < CAPTURE.beamWidth / 2;
    const withinY =
      this.player.y > this.beam.y && this.player.y < this.beam.y + CAPTURE.beamLength;
    if (!withinX || !withinY) return;

    const pull = this.beam.x - this.player.x;
    this.player.x += Math.sign(pull) * Math.min(Math.abs(pull), 2);
    this.player.y -= CAPTURE.pullStrength * (delta / 1000);

    if (this.player.y < this.beam.y + CAPTURE.captureDepth) this.capturePlayer();
  }

  cullProjectiles() {
    this.bullets.getChildren().forEach((bullet) => {
      if (bullet.active && bullet.y < -20) bullet.destroy();
    });

    this.enemyBullets.getChildren().forEach((bullet) => {
      if (!bullet.active) return;
      const offScreen =
        bullet.y > SCREEN.height + 20 || bullet.x < -20 || bullet.x > SCREEN.width + 20;
      if (offScreen) bullet.destroy();
    });
  }

  checkStageComplete() {
    if (this.stageResolving || this.enemies.countActive(true) > 0) return;
    // Enemies launch on a stagger, so an empty group during the launch window
    // is not a cleared stage.
    if (this.formationElapsed < 2000) return;
    this.completeStage();
  }

  // ---------------------------------------------------------------- helpers

  slotPosition(slot) {
    const centreX = clampFormationCentre(SCREEN.width / 2, SCREEN.width, {
      spacingX: FORMATION.spacingX,
      breathScale: this.currentBreath,
      margin: FORMATION.margin,
    });

    return slotWorldPosition(slot, {
      centreX,
      topY: FORMATION.topY,
      spacingX: FORMATION.spacingX,
      spacingY: FORMATION.spacingY,
      breathScale: this.currentBreath,
      swayX: this.currentSway,
    });
  }

  addScore(points) {
    const previous = this.score;
    this.score += points;

    const earned = extraLivesEarned(previous, this.score, this.bonusScheme);
    if (earned > 0) {
      this.lives += earned;
      this.showBanner('EXTRA LIFE', 900);
      this.sfx.extraLife.play({ volume: 0.5 });
    }

    if (this.score > this.highScore) this.highScore = this.score;
    this.refreshHud();
  }

  showBanner(text, durationMs) {
    this.bannerText.setText(text).setVisible(true);
    this.time.delayedCall(durationMs, () => this.bannerText.setVisible(false));
  }

  refreshHud() {
    this.drawScores();
    this.highScoreText.setText(String(this.highScore));
    this.drawLives();
    this.drawFlags();
  }

  /**
   * Both score columns, and the blink that says which of them is live.
   *
   * The active player's column reads the live score; the other reads whatever
   * was banked when their turn ended, so a player watching their opponent can
   * see exactly how far ahead they need to get.
   */
  drawScores() {
    this.session.players.forEach((player, index) => {
      const live = index === this.turnOwner;
      this.playerScores[index].setText(String(live ? this.score : player.score));
    });

    // The blink follows the ship, not the session: it marks who is flying, and
    // through the pause after a death nobody has taken over yet.
    if (this.blinkingColumn === this.turnOwner) return;
    this.blinkingColumn = this.turnOwner;

    this.playerBlinks.forEach((blink, index) => {
      if (index === this.turnOwner) {
        blink.restart();
        return;
      }
      blink.pause();
      this.playerHeadings[index].setAlpha(1);
    });
  }

  drawLives() {
    this.lifeIcons.forEach((icon) => icon.destroy());
    this.lifeIcons = [];

    // Spaced wider than the icons are drawn, so a row of spare ships reads as
    // separate ships rather than one smear, and capped at the number that fits
    // beside the stage flags: a player on a good run can bank more spare ships
    // than the row is wide, and the arcade stops drawing them rather than
    // running them into the flags.
    const shown = Math.min(Math.max(this.lives - 1, 0), LIFE_ICONS_SHOWN);

    for (let i = 0; i < shown; i += 1) {
      const icon = this.add
        .image(
          16 + i * 36,
          SCREEN.height - 14,
          shipTextureKey('player', SHIP_ART.lifeIconPixelSize),
        )
        .setOrigin(0, 1)
        .setDepth(20);

      this.lifeIcons.push(applyShipArt(icon, 'player', SHIP_ART.lifeIconPixelSize));
    }
  }

  /**
   * Build one flag texture per denomination.
   *
   * Generated rather than loaded because the repo ships no flag artwork. Each
   * is drawn once into a texture and then instanced as an image, so a stage
   * showing nine flags costs nine sprites rather than nine redraws.
   */
  drawFlags() {
    this.flagIcons.forEach((icon) => icon.destroy());
    this.flagIcons = [];

    // Laid out right to left, highest denomination outermost, which is the
    // order `stageFlags` returns them in.
    let x = SCREEN.width - 12;
    for (const flag of stageFlags(this.stage)) {
      for (let i = 0; i < flag.count; i += 1) {
        this.flagIcons.push(
          this.add
            .image(x, SCREEN.height - 14, flagTextureKey(flag.value))
            .setOrigin(1, 1)
            .setDepth(20),
        );
        // Ones are drawn shoulder to shoulder, as the arcade does; the larger
        // denominations get a little air so the groups stay countable.
        x -= flag.value === 1 ? FLAG_DRAWN_WIDTH + 2 : FLAG_DRAWN_WIDTH + 6;
      }
    }
  }

  clearTimers() {
    this.assemblyTimer?.remove();
    this.assemblyTimer = null;
    this.captureTimer?.remove();
    this.captureTimer = null;
    // The attack scheduler is not a timer, but it stops with them.
    this.attackActive = false;
  }
}
