/**
 * The play scene.
 *
 * This file orchestrates. Every rule it needs, where the formation sits, what a
 * kill is worth, whether this stage is a Challenging Stage, what the capture
 * machine allows next, lives in a pure module under `src/systems` and is unit
 * tested there. What remains here is Phaser: sprites, input, timers, and
 * collision callbacks.
 *
 * That split is deliberate. The version this replaced was a single 867-line
 * class where the same concerns were interleaved, which is how it grew four
 * independent booleans to track one capture sequence and could represent
 * states that should not exist.
 */

import {
  CAPTURE,
  DIVE,
  DUAL_FIGHTER_OFFSET_X,
  FORMATION,
  LIFE_ICONS_SHOWN,
  PLAYER,
  SCREEN,
  SHIP_ART,
  SHIP_DRAWN_PX,
  SPRITE_SCALE,
  SPRITE_SOURCE_PX,
  CHALLENGING,
  TRANSFORM,
  ANIMATION,
  FLAG_ART,
} from '../config.js';
import {
  flapFrameAt,
  quantizeHeading,
  explosionFrameAt,
  spinAngleAt,
} from '../systems/animation.js';
import { beamStripsAt } from '../systems/beam.js';
import { EXPLOSION_SPRITES, frameCount } from '../art/pixelArt.js';
import {
  EnemyType,
  buildFormationSlots,
  buildEntryGroups,
  breathScaleAt,
  swayOffsetAt,
  slotWorldPosition,
  clampFormationCentre,
  FORMATION_SIZE,
} from '../systems/formation.js';
import {
  divePath,
  returnPath,
  challengingPath,
  captiveEscapePath,
  entrySpawnPoint,
  createEntryFlightState,
  createDiveFlightState,
  pointOnPath,
} from '../systems/paths.js';
import {
  createFlight,
  advanceFlight,
  isFlightComplete,
  flightProgress,
  flightTransform,
  createLiveFlight,
  advanceLiveFlight,
  liveFlightTransform,
  isLiveFlight,
  isLiveFlightDone,
  liveFlightHomed,
} from '../systems/flight.js';
import {
  BOMB_ARM_FRAMES,
  BOMB_DROP_MIN_Y,
  BOMB_FALL_PER_FRAME,
  BOMB_SPACING_FRAMES,
  advanceNoFire,
  advanceScheduler,
  bombAimVx,
  createAttackScheduler,
  createNoFireState,
  nextBombDrop,
} from '../systems/attack.js';
import { FRAME_MS, PATHCODE_FPS } from '../systems/pathcode.js';
import { DIP_DEFAULTS, bonusSchemeFor, loadDips } from '../systems/dips.js';
import {
  STARFIELD_SCROLL,
  advanceStarfield,
  createStarfield,
  setStarfieldScroll,
  visibleStars,
} from '../systems/starfield.js';
import {
  scoreFor,
  extraLivesEarned,
  PERFECT_BONUS,
  CAPTURED_FIGHTER_POINTS,
  transformKillPoints,
  TRANSFORM_SET_SIZE,
  CHALLENGING_STAGE_HIT_POINTS,
} from '../systems/scoring.js';
import {
  isChallengingStage,
  stageDifficulty,
  stageFlags,
  enemiesFireDuringEntry,
  enemiesBomb,
  captureAllowed,
  challengingPatternIndex,
  challengingRoster,
  transformTypeFor,
  caravanFor,
  RANK_NAMES,
  nextStage,
} from '../systems/stages.js';
import {
  createSession,
  activePlayer,
  withActive,
  loseShip,
  playerLabel,
} from '../systems/players.js';
import { demoInput, DEMO_DURATION_MS } from '../systems/demo.js';
import { isTap, mergeHeld, padHeld, touchSteer } from '../systems/controls.js';
import { applyCabinet } from '../art/crt.js';
import {
  CaptureState,
  CaptureEvent,
  RescueOutcome,
  transition,
  resolveCaptorDestroyed,
  isBeamDangerous,
  hasDualFighter,
  bulletLimit,
  captiveCanBomb,
} from '../systems/capture.js';
import { resolveStorage, loadScoreTable, loadRank } from '../systems/persistence.js';
import {
  createExplosionTextures,
  createFlagTextures,
  createShipTextures,
  createTransformTextures,
  explosionTextureKey,
  flagTextureKey,
  shipTextureKey,
  FLAG_DRAWN_WIDTH,
} from '../art/textures.js';
import { applyShipArt, localArtFrames, queueLocalArt } from '../art/localArt.js';
import { arcadeText, installArcadeFont } from '../art/font.js';
import { installSoundBank } from '../audio/soundBank.js';
import { queueLocalAudio } from '../audio/localAudio.js';
import { recordShot, recordHit } from '../systems/stats.js';
import {
  SOUND_NAMES,
  challengeResultSound,
  deathSoundFor,
  playerShotSound,
} from '../systems/audio.js';
import {
  EnemyMode,
  createEnemy,
  isDiving,
  canBeginDive,
  settleIntoFormation,
  showBossDamage,
  createTransformEnemy,
} from '../entities/enemy.js';

/**
 * ROM canvas (224 x 288) to this screen: the x3 scale adapter. Bomb gates
 * and speeds are ROM-denominated in `attack.js` and converted here.
 */
const ROM_TO_SCREEN = SCREEN.height / 288;

export class GameScene extends Phaser.Scene {
  constructor() {
    super({ key: 'GameScene' });
  }

  preload() {
    // Only the projectiles and the two effects are loaded. Every ship in the
    // game is generated from the pixel grids in `src/art` (see
    // `createShipTextures`), and the starfield is generated by
    // `src/systems/starfield.js` rather than drawn.
    this.load.image('bullet', 'assets/images/player_laser.png');
    this.load.image('laser', 'assets/images/enemy_laser.png');

    // A local checkout may keep its own ship artwork; see `src/art/localArt.js`.
    // Absent, this is one 404 and the drawn ships are used.
    queueLocalArt(this);

    // The same arrangement for audio, and the only thing loaded for it. Every
    // sound is synthesised in `create`; this probe is the one way the cabinet's
    // own samples can get in, and only on a machine that already has them.
    queueLocalAudio(this);
  }

  /**
   * How this game was started.
   *
   * Three things arrive from outside: how many players pressed start, whether
   * this is the attract screen playing itself, and the operator's difficulty
   * rank. All three have defaults, so `scene.start('GameScene')` with nothing
   * at all is a one-player game at the factory rank -- which is what the
   * results screen's "play again" does.
   */
  init(data) {
    this.demo = data?.demo === true;
    this.storage = resolveStorage(globalThis.localStorage);
    // The demo is not a game the operator's settings apply to: it is the
    // machine showing what the game looks like, and it should look like the one
    // a new player would get.
    this.rank = this.demo ? 0 : loadRank(this.storage);

    // The operator's switch block decides how many fighters a credit buys
    // and which bonus scheme pays. A demo plays the factory machine.
    this.dips = this.demo ? { ...DIP_DEFAULTS } : loadDips(this.storage);
    this.bonusScheme = bonusSchemeFor(this.dips);

    this.session = createSession({
      playerCount: this.demo ? 1 : (data?.playerCount ?? 1),
      startingLives: this.dips.lives,
    });

    // The no-fire bug, if the operator has switched it on. Once triggered it
    // holds until the "machine" is power cycled -- the registry survives
    // scene restarts, so only a page reload clears it, which is the bug's
    // real cure.
    this.noFire = {
      ...createNoFireState(),
      triggered: this.registry.get('noFireTriggered') === true,
    };
  }

  create() {
    // The live copies of the active player's game. They are held here rather
    // than read out of the session every frame because they change many times a
    // second; `bankTurn` folds them back when the turn ends.
    this.loadTurn();
    // The number in the HUD is the top of the board, not a second high score
    // kept beside it. A cabinet whose header disagreed with its own BEST 5
    // would be showing one of the two wrong.
    this.highScore = loadScoreTable(this.storage)[0].score;
    this.captureState = CaptureState.IDLE;
    this.shotIndex = 0;

    this.isGameOver = false;
    this.isInvulnerable = false;
    this.frozen = false;
    this.stageResolving = false;
    this.formationElapsed = 0;
    this.challengingHits = 0;
    this.currentBreath = 1;
    this.currentSway = 0;

    // Generated rather than loaded: every ship in the game is pixel art
    // authored in `src/art`, so the textures are built once here, before
    // anything asks for one.
    createShipTextures(this);
    createTransformTextures(this);
    createExplosionTextures(this);
    installArcadeFont(this);

    // The formation-wide wing frame currently showing. One clock for the
    // whole board; see `flapFrameAt`.
    this.flapFrame = 0;

    this.createWorld();
    this.createPlayer();
    this.createGroups();
    this.createHud();
    this.createInput();
    this.registerCollisions();

    // The volume pot and the monitor overlay, as the operator left them.
    applyCabinet(this, SCREEN);

    // Brief grace on the opening spawn so the arriving wave cannot land a hit
    // before the player has had a chance to move.
    this.makeInvulnerable(PLAYER.invulnerableMs);

    if (this.demo) this.beginDemo();

    // A two-player game says whose turn it is before the first wave, the way
    // the cabinet does. A one-player game does not, because there is nobody to
    // distinguish it from.
    if (this.session.playerCount > 1) {
      this.showBanner(playerLabel(this.session.active), 1500);
      this.time.delayedCall(1500, () => {
        if (!this.isGameOver) this.beginStage(this.stage);
      });
      return;
    }

    this.beginStage(this.stage);
  }

  // ------------------------------------------------------------------ turns

  /**
   * Load the active player's game into the live fields.
   *
   * Two-player Galaga is alternating, so everything the machine tracks it
   * tracks twice and swaps the pair over at a handover. This is that swap in
   * one direction; `bankTurn` is the other.
   */
  loadTurn() {
    const player = activePlayer(this.session);

    // Which player the live fields below belong to. It is not always the
    // session's active player: `loseShip` hands the machine over at the instant
    // a ship is destroyed, but the outgoing player's ship is still exploding
    // and their score is still in `this.score` for another second and a half.
    // Without this the HUD spent that second showing the dying player's score
    // in the incoming player's column.
    this.turnOwner = player.index;

    this.score = player.score;
    this.lives = player.lives;
    this.stage = player.stage;
    // Stages *played*, which is not the same as the stage number once the
    // counter has rolled over past 255. Difficulty is driven from this so a
    // player who gets that far is not handed the opening round back.
    this.round = player.round;
    this.stats = player.stats;
  }

  /** Fold the live fields back into the active player's record. */
  bankTurn() {
    this.session = withActive(this.session, {
      score: this.score,
      lives: this.lives,
      stage: this.stage,
      round: this.round,
      stats: this.stats,
    });
  }

  /**
   * Hand the machine to the other player.
   *
   * Everything on the board belongs to the outgoing player, so all of it goes:
   * the formation, whatever was diving, any beam, and any capture in progress.
   * The incoming player restarts their *own* stage from its opening wave, which
   * is what the arcade does -- a turn is a stage attempt, and the stage the
   * other player was half way through is none of their business.
   */
  handOverTurn() {
    this.clearTimers();
    this.stageAdvanceTimer?.remove();
    this.stageAdvanceTimer = null;
    // Held until `beginStage` clears it. Without it the empty board left by the
    // teardown below reads as a cleared stage, and the incoming player is
    // credited with finishing the stage the outgoing one died on.
    this.stageResolving = true;

    this.enemies.clear(true, true);
    this.enemyBullets.clear(true, true);
    this.bullets.clear(true, true);
    this.clearCaptive();
    this.clearDualFighter();
    this.clearBeam();
    this.captor = null;
    this.captureState = CaptureState.IDLE;
    this.sfx.enemyDive.stop();

    this.loadTurn();
    this.refreshHud();

    this.player.enableBody(true, SCREEN.width / 2, PLAYER.y, true, true);
    this.player.setAngle(0);
    this.makeInvulnerable(PLAYER.invulnerableMs);

    this.showBanner(playerLabel(this.session.active), 1600);
    this.time.delayedCall(1600, () => {
      if (this.isGameOver) return;
      this.beginStage(this.stage);
    });
  }

  // ------------------------------------------------------------------ setup

  createWorld() {
    // The 63-star hardware field. It streams during play and stops dead
    // while no fighter is on the board, which is the cabinet's own tell that
    // the world has paused; see `updateStarfield`.
    this.starfield = setStarfieldScroll(createStarfield(), STARFIELD_SCROLL.game);
    this.starLayer = this.add.graphics().setScrollFactor(0);

    // Synthesised into the audio cache here, in `create`, rather than fetched
    // in `preload`: nothing is downloaded, and by now the loader has finished,
    // so anything a local checkout supplied is already in the cache and is
    // left where it is. See `src/audio/soundBank.js`.
    installSoundBank(this);

    this.sfx = Object.fromEntries(SOUND_NAMES.map((key) => [key, this.sound.add(key)]));

    // Galaga plays a low pulse under the whole board. It is the thing that
    // makes a cleared screen feel quiet, so it runs for as long as the scene
    // does rather than being started and stopped per stage.
    // Stopped by key first: replaying the scene builds a second Sound object,
    // and two copies of a loop is a drone rather than a pulse.
    this.sound.stopByKey('ambient');
    this.sfx.ambient.play({ volume: 0.18, loop: true });
  }

  createPlayer() {
    this.player = this.physics.add
      .sprite(SCREEN.width / 2, PLAYER.y, shipTextureKey('player'))
      .setCollideWorldBounds(true);
    applyShipArt(this.player, 'player');

    // The same 62% body every enemy gets. The fighter is drawn as a narrow
    // hull inside a 48px frame, and a body filling that frame would have the
    // player shot down by bombs passing through empty space beside the wings.
    this.player.body.setSize(this.player.width * 0.62, this.player.height * 0.62, true);
    this.player.body.setAllowGravity(false);
    this.dualFighter = null;
  }

  createGroups() {
    this.enemies = this.physics.add.group();
    this.bullets = this.physics.add.group();
    this.enemyBullets = this.physics.add.group();

    // The dual fighter lives in a group of its own so its collisions can be
    // registered once here, rather than wired up and torn down every time one
    // is earned and lost.
    this.wingman = this.physics.add.group();

    // A held captive is a target. Shooting your own fighter is a legal, scored
    // move in the arcade, so the captive needs a body and an overlap of its
    // own rather than being a decorative image riding on its captor.
    this.captives = this.physics.add.group();
  }

  /**
   * The cabinet's own header: 1UP over one running score on the left, HIGH
   * SCORE over the board's best in the middle, 2UP over the other on the right.
   *
   * The blink is not decoration -- it marks whose turn is live. Which is why
   * only the column belonging to the player currently flying blinks, and why in
   * a one-player game the 2UP column is drawn dim and empty: that is exactly
   * what a two-player cabinet looks like when one person is playing, and it is
   * what gives the blink on the left something to mean.
   */
  createHud() {
    const heading = { tint: 0xff4444 };
    const value = { tint: 0xffffff };

    this.playerHeadings = [
      arcadeText(this, 20, 12, '1UP', heading).setDepth(20),
      arcadeText(this, SCREEN.width - 20, 12, '2UP', heading).setOrigin(1, 0).setDepth(20),
    ];

    arcadeText(this, SCREEN.width / 2, 12, 'HIGH SCORE', heading).setOrigin(0.5, 0).setDepth(20);

    this.playerScores = [
      arcadeText(this, 20, 32, '', value).setDepth(20),
      arcadeText(this, SCREEN.width - 20, 32, '', value).setOrigin(1, 0).setDepth(20),
    ];

    // One blink tween per column, both created up front and paused: a handover
    // moves the blink by pausing one and resuming the other, so the tweens are
    // never rebuilt and the two can never end up blinking together.
    this.playerBlinks = this.playerHeadings.map((text) =>
      this.tweens.add({
        targets: text,
        alpha: 0.15,
        duration: 500,
        yoyo: true,
        repeat: -1,
        paused: true,
      }),
    );

    if (this.session.playerCount < 2) {
      this.playerHeadings[1].setTint(0x663333);
      this.playerScores[1].setTint(0x555555);
    }

    // The rank the operator left the machine on. Drawn small and out of the
    // way, because on a real cabinet it is not on the screen at all -- it is a
    // switch inside the box -- but a browser has no box, and a player who has
    // set it to D deserves to be told why the first screen is shooting at them.
    if (this.rank > 0) {
      arcadeText(this, SCREEN.width / 2, 54, `RANK ${RANK_NAMES[this.rank]}`, { tint: 0x886644 })
        .setOrigin(0.5, 0)
        .setDepth(20);
    }

    // Which column is currently blinking, so that `refreshHud` -- which runs on
    // every point scored -- can leave a running tween alone instead of
    // restarting it several times a second.
    this.blinkingColumn = -1;
    this.highScoreText = arcadeText(this, SCREEN.width / 2, 32, '', { tint: 0xffcc00 })
      .setOrigin(0.5, 0)
      .setDepth(20);

    this.bannerText = arcadeText(this, SCREEN.width / 2, SCREEN.height / 2, '', { scale: 1.5 })
      .setCenterAlign()
      .setOrigin(0.5)
      .setDepth(30)
      .setVisible(false);

    this.lifeIcons = [];
    this.flagIcons = [];
    createFlagTextures(this);
    this.refreshHud();
  }

  createInput() {
    this.keys = this.input.keyboard.addKeys({
      left: 'A',
      right: 'D',
      altLeft: 'LEFT',
      altRight: 'RIGHT',
    });

    // A second touch point, so one finger can steer while another fires.
    this.input.addPointer(1);
    this.steerPointer = null;

    // During a demo the controls belong to the machine, and the only thing
    // any control does is what it does on a cabinet mid-attract: start a
    // real game. That includes a tap on the glass and a pad's buttons.
    if (this.demo) {
      this.input.keyboard.once('keydown-SPACE', () => this.startRealGame(1));
      this.input.keyboard.once('keydown-ONE', () => this.startRealGame(1));
      this.input.keyboard.once('keydown-TWO', () => this.startRealGame(2));
      this.input.once('pointerdown', () => this.startRealGame(1));
      this.input.gamepad?.once('down', () => this.startRealGame(1));
      return;
    }

    // Movement is a held state and is read per frame; firing is an event.
    // Polling `JustDown` for the trigger loses any press that begins and ends
    // inside one frame, and tapping faster than the refresh rate is exactly
    // what a two-shot limit teaches a player to do. The `repeat` guard is what
    // stops a held key turning into the operating system's key-repeat rate.
    this.input.keyboard.on('keydown-SPACE', (event) => {
      if (!event.repeat) this.fire();
    });

    // The freeze switch. The cabinet's DIP sheet has one -- MAME calls it
    // FREEZE -- and flipping it stops the whole machine mid-frame until it is
    // flipped back. P is that switch; it is not a menu and it is not stored.
    this.input.keyboard.on('keydown-P', () => this.toggleFreeze());

    // Touch: the first finger down is the stick -- the ship chases its
    // column, read per frame in `updatePlayer` -- and any second finger is
    // the fire button. A finger that comes and goes without steering is a
    // tap, and a tap is a trigger pull.
    this.input.on('pointerdown', (pointer) => {
      if (this.steerPointer === null) {
        this.steerPointer = pointer;
        return;
      }
      if (pointer !== this.steerPointer) this.fire();
    });
    this.input.on('pointerup', (pointer) => {
      if (pointer !== this.steerPointer) return;
      this.steerPointer = null;
      const heldMs = pointer.upTime - pointer.downTime;
      const movedPx = Math.abs(pointer.x - pointer.downX);
      if (isTap(heldMs, movedPx)) this.fire();
    });

    // A pad's face buttons are the fire button; held direction is read per
    // frame in `updatePlayer` through `padState`.
    this.input.gamepad?.on('down', (pad, button) => {
      if (button.index === 0 || button.index === 1) this.fire();
    });
  }

  /**
   * The pad's held direction, flattened to the shape `controls.js` reads.
   * Null when nothing is connected, which `padHeld` treats as neutral.
   */
  padState() {
    const pad = this.input.gamepad?.getPad(0);
    if (!pad) return null;
    return {
      axisX: pad.axes.length > 0 ? pad.axes[0].getValue() : 0,
      dpadLeft: pad.left,
      dpadRight: pad.right,
    };
  }

  /**
   * The freeze switch, thrown or released.
   *
   * Freezing is total the way the DIP switch is total: physics, tweens, the
   * clock and the sound all stop, and nothing advances until the switch is
   * released. `update` returns immediately while frozen, so the starfield
   * stops with everything else.
   */
  toggleFreeze() {
    if (this.isGameOver) return;
    this.frozen = !this.frozen;

    if (this.frozen) {
      this.physics.world.pause();
      this.tweens.pauseAll();
      this.time.paused = true;
      this.sound.pauseAll();
      this.freezeLabel = arcadeText(this, SCREEN.width / 2, SCREEN.height / 2, 'FREEZE', {
        tint: 0x44ff88,
        scale: 1.5,
      })
        .setOrigin(0.5)
        .setDepth(40);
      return;
    }

    this.physics.world.resume();
    this.tweens.resumeAll();
    this.time.paused = false;
    this.sound.resumeAll();
    this.freezeLabel?.destroy();
    this.freezeLabel = null;
  }

  // ------------------------------------------------------------------- demo

  /**
   * Put the machine in charge of the fighter.
   *
   * The demo is a real game of Galaga in every respect except who is holding
   * the stick: the same stages, the same formation, the same capture, the same
   * scoring. What changes is that `updatePlayer` reads `demoInput` instead of
   * the keyboard, that the screen says so, and that nothing about it is ever
   * written to the score table -- a machine that put its own demo on the board
   * would be filling the board with itself.
   */
  beginDemo() {
    // Well clear of the row the fighter flies in: the machine's own ship spends
    // the whole demo travelling along the bottom of the screen, and text behind
    // it is text nobody can read.
    this.demoLabel = arcadeText(this, SCREEN.width / 2, SCREEN.height * 0.72, 'DEMO PLAY', {
      tint: 0xffcc00,
      scale: 1.5,
    })
      .setOrigin(0.5)
      .setDepth(30);

    this.tweens.add({
      targets: this.demoLabel,
      alpha: 0.25,
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    arcadeText(this, SCREEN.width / 2, SCREEN.height * 0.72 + 30, 'PUSH START BUTTON   1P: SPACE   2P: 2', {
      tint: 0x8899bb,
    })
      .setOrigin(0.5)
      .setDepth(30);

    this.demoTimer = this.time.delayedCall(DEMO_DURATION_MS, () => this.endDemo());
  }

  /** Hand the screen back to the attract loop. */
  endDemo() {
    if (!this.demo) return;
    this.demo = false;
    this.isGameOver = true;
    this.clearTimers();
    this.sound.stopAll();
    this.scene.start('TitleScene');
  }

  /** Someone pressed start while the machine was playing: give them the game. */
  startRealGame(playerCount) {
    if (!this.demo) return;
    this.demo = false;
    this.isGameOver = true;
    this.demoTimer?.remove();
    this.clearTimers();
    this.sound.stopAll();
    this.sound.play('coin', { volume: 0.5 });
    this.scene.start('GameScene', { playerCount });
  }

  /**
   * The board as the demo pilot sees it.
   *
   * Deliberately narrow: positions and nothing else. The pilot is a pure
   * function of this, which is what lets `tests/demo.test.js` fly it without a
   * canvas, and it is why the pilot cannot cheat by reading a timer or a
   * random seed the player has no access to.
   */
  demoBoard() {
    return {
      playerX: this.player.x,
      playerY: this.player.y,
      screenWidth: SCREEN.width,
      margin: SHIP_DRAWN_PX / 2,
      bombs: this.enemyBullets
        .getChildren()
        .filter((bullet) => bullet.active)
        .map((bullet) => ({ x: bullet.x, y: bullet.y })),
      targets: this.enemies
        .getChildren()
        .filter((enemy) => enemy.active)
        .map((enemy) => ({ x: enemy.x, y: enemy.y })),
      beam:
        this.beam && isBeamDangerous(this.captureState)
          ? { x: this.beam.x, width: CAPTURE.beamWidth }
          : null,
    };
  }

  registerCollisions() {
    this.physics.add.overlap(this.bullets, this.enemies, (bullet, enemy) => {
      bullet.destroy();
      this.onEnemyHit(enemy);
    });

    this.physics.add.overlap(this.player, this.enemies, (_player, enemy) => {
      // Challenging Stage enemies fly through without attacking, exactly as
      // they do in the arcade. Their pass crosses the player's lane, so this
      // guard is what keeps the bonus round a bonus.
      if (this.challenging) return;
      if (!this.canBeHurt() || !enemy.active) return;
      this.destroyEnemy(enemy, false);
      this.onPlayerHit();
    });

    this.physics.add.overlap(this.player, this.enemyBullets, (_player, bullet) => {
      if (!this.canBeHurt() || !bullet.active) return;
      bullet.destroy();
      this.onPlayerHit();
    });

    // The second ship is as solid as the first, which is what the doubled
    // firepower is paid for.
    this.physics.add.overlap(this.wingman, this.enemies, (_wingman, enemy) => {
      if (this.challenging) return;
      if (!this.canBeHurt() || !enemy.active) return;
      this.destroyEnemy(enemy, false);
      this.onPlayerHit();
    });

    // Shooting your own captured fighter. Worth 1,000 and loses the ship for
    // good -- the player gives up any chance of the dual fighter to take the
    // points, which is the trade the arcade offers and the reason the captive
    // is left hanging there in the formation rather than being untouchable.
    this.physics.add.overlap(this.bullets, this.captives, (bullet, captive) => {
      if (!bullet.active || !captive.active) return;
      bullet.destroy();
      this.onCaptiveShot();
    });

    this.physics.add.overlap(this.wingman, this.enemyBullets, (_wingman, bullet) => {
      if (!this.canBeHurt() || !bullet.active) return;
      bullet.destroy();
      this.onPlayerHit();
    });

    // A captive that has broken loose is flying at the player and can ram
    // them, exactly as a diving enemy can. While it is still pinned under its
    // captor it is only a target, so the guard is on the escape flight rather
    // than on the sprite existing.
    for (const ship of [this.player, this.wingman]) {
      this.physics.add.overlap(ship, this.captives, (_ship, captive) => {
        if (!captive.flight || !this.canBeHurt() || !captive.active) return;
        this.clearCaptive();
        this.onPlayerHit();
      });
    }
  }

  // ----------------------------------------------------------------- stages

  beginStage(stage) {
    // Cancel any stage advance still pending, so two stages can never be
    // started from one clear.
    this.stageAdvanceTimer?.remove();
    this.stageAdvanceTimer = null;

    this.stageResolving = false;
    this.formationElapsed = 0;
    this.challengingHits = 0;
    this.difficulty = stageDifficulty(this.round, this.rank);
    this.challenging = isChallengingStage(stage);
    this.transformType = transformTypeFor(stage);

    // The stage's attack scheduler: per-type launch counters out of the
    // difficulty row. It starts counting when the wave finishes assembling.
    this.attack = createAttackScheduler(this.difficulty);
    this.attackActive = false;

    // A docked dual fighter carries over into the next stage; anything else
    // mid-sequence does not. Clearing the state but leaving the second ship on
    // screen would have left it firing two shots against a two-shot limit and
    // no longer able to absorb a hit.
    if (!hasDualFighter(this.captureState)) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      this.clearDualFighter();
    }

    this.captor = null;
    this.clearCaptive();
    this.clearBeam();
    this.clearTimers();

    // STAGE n, then READY, then the wave -- the cabinet's own cadence, cut
    // inside the same 1800ms the single banner used to hold, so nothing about
    // when the formation actually arrives has moved.
    this.showBanner(this.challenging ? 'CHALLENGING STAGE' : `STAGE ${stage}`, 1100);
    this.time.delayedCall(1100, () => {
      if (!this.isGameOver) this.showBanner('READY', 700);
    });
    this.sfx[this.challenging ? 'challengeStart' : 'stageFlag'].play({ volume: 0.5 });
    this.refreshHud();

    this.time.delayedCall(1800, () => {
      if (this.isGameOver) return;
      if (this.challenging) {
        this.launchChallengingStage();
      } else {
        this.launchFormation();
      }
    });
  }

  /**
   * Bring the wave on as five flights of eight, in this stage's entrance
   * pattern.
   *
   * The pattern is a property of the stage, not of the flight: all five
   * flights of a wave belong to one of the arcade's three entrances, which is
   * what makes an entrance recognisable rather than a shuffle. Within it, each
   * member carries the curve it flies and its step in the launch order, so the
   * both-sides pattern can put two arrivals in the air at once while the other
   * two stay single file.
   *
   * All forty sprites are created up front, parked at their curve's off-screen
   * start, and only their flights are staggered. That matters: the stage is
   * considered clear when no enemy is left alive, so an enemy waiting to
   * launch has to already exist.
   */
  launchFormation() {
    // Round 1 holds fire through the whole assembly; from round 2 the arriving
    // wave bombs on its way in.
    const entryFire = enemiesFireDuringEntry(this.stage);
    const slots = buildFormationSlots();
    // The caravan is a property of the stage *and* the operator's rank, which
    // is the arcade's own `d_combat_stg_dat_idx[rank * 17 + row]`. Every member
    // carries the shape it flies, whether that shape is mirrored, and the beat
    // it launches on, all decoded out of the row's path bytes.
    const groups = buildEntryGroups(caravanFor(this.stage, this.rank));

    groups.forEach((group) => {
      const groupDelay = group.index * FORMATION.groupIntervalMs;

      group.members.forEach(({ slotIndex, pathVariant, mirrored, step }) => {
        const slot = slots[slotIndex];
        // Spawn where the db_2A6C variant row puts this pair member: bit 6
        // of the wave byte picks the member AND negates its rotations.
        const start = entrySpawnPoint(pathVariant, mirrored ? 1 : 0, SCREEN);
        const enemy = createEnemy(this, this.enemies, slot, start, this.flapFrame);
        // An arriving ship gets at most one shot on the way in, and only from
        // stage 2. Interim: the ROM masks fly-in bombing per creature through
        // the caravan header byte and the d_2908 capability bits; Task 4's
        // caravan machine wires those, and until then a one-in-four draw
        // stands in for the bit distribution.
        enemy.bombMask = entryFire && !this.noFire.triggered && Math.random() < 0.25 ? 1 : 0;
        enemy.bombCountdownMs = BOMB_ARM_FRAMES * FRAME_MS;

        this.time.delayedCall(groupDelay + step * FORMATION.entryStaggerMs, () => {
          if (!enemy.active) return;
          // A LIVE flight on the ROM's path machine: the block flies its
          // segments and the FB turn-home glides onto the slot's live,
          // swaying position, fed in as homeTarget every frame. Formation
          // object ids stay clear of the transient window (0x38-0x3E) so
          // the F7 gate never fires for a formation member; Task 4's
          // caravan machine launches the real transients through it.
          enemy.flight = createLiveFlight(createEntryFlightState(pathVariant, mirrored ? 1 : 0), SCREEN);
        });
      });
    });

    this.scheduleCaptureAttempts();

    // The arcade lets the wave finish arriving before anything attacks, so the
    // entry choreography is never cut across by a dive.
    this.assemblyTimer = this.time.delayedCall(this.assemblyDurationMs(groups), () => {
      this.assemblyTimer = null;
      if (this.isGameOver || this.stageResolving) return;
      // The arcade lets the wave finish arriving before anything attacks;
      // from here the per-type launch counters run.
      this.attackActive = true;
    });
  }

  /**
   * How long the whole wave takes, from the first launch to the last dock.
   *
   * Read off the last member's step rather than assumed to be eight, because a
   * both-sides flight launches its eight in four paired steps and is home
   * sooner. Taking the maximum keeps the "nothing attacks until everyone has
   * landed" rule true for every pattern.
   */
  assemblyDurationMs(groups) {
    const lastStep = Math.max(
      ...groups.flatMap((group) => group.members.map((member) => member.step)),
    );

    return (
      (groups.length - 1) * FORMATION.groupIntervalMs +
      lastStep * FORMATION.entryStaggerMs +
      FORMATION.entryDurationMs
    );
  }

  /**
   * Challenging Stage: forty enemies fly through and never fire or dive.
   * Clearing all of them pays the perfect bonus.
   *
   * Structured like the entry wave, as five flights of eight rather than one
   * forty-ship stream. Everyone in a flight shares one route and one lane, so
   * the eight arrive nose to tail and can be swept with a single held line of
   * fire; the lane changes between flights so the pattern is traced out across
   * the field instead of being redrawn in the same place five times.
   */
  launchChallengingStage() {
    const pattern = challengingPatternIndex(this.stage) ?? 0;
    // A bonus round is not the attack formation flying a different route: it is
    // one rank of enemy plus four Boss Galaga. The slots are still the
    // formation's, because they are what splits forty ships into five flights
    // of eight, but who sits in them comes from `challengingRoster`.
    const roster = challengingRoster(this.stage) ?? [];
    const slots = buildFormationSlots().map((slot, index) => ({
      ...slot,
      type: roster[index] ?? slot.type,
    }));

    buildEntryGroups().forEach((group) => {
      const groupDelay = group.index * CHALLENGING.groupIntervalMs;
      // One offset for the whole flight: same curve, same lane, single file.
      const path = challengingPath(pattern, group.index, SCREEN);

      group.slotIndices.forEach((slotIndex, position) => {
        const enemy = createEnemy(
          this,
          this.enemies,
          slots[slotIndex],
          pointOnPath(path, 0),
          this.flapFrame,
        );
        enemy.mode = EnemyMode.PASSING;

        this.time.delayedCall(groupDelay + position * CHALLENGING.staggerMs, () => {
          if (!enemy.active) return;
          enemy.flight = createFlight(path, CHALLENGING.passDurationMs);
        });
      });
    });
  }

  completeStage() {
    if (this.stageResolving) return;
    this.stageResolving = true;
    this.clearTimers();

    if (this.challenging) {
      const perfect = this.challengingHits === FORMATION_SIZE;
      this.sfx.challengeClear.play({ volume: 0.5 });
      this.sfx[challengeResultSound(this.challengingHits, FORMATION_SIZE)].play({ volume: 0.6 });

      // The cabinet's own wording. A round that fell short reports the total
      // already paid at 100 a hit rather than paying it again here; only the
      // perfect bonus is awarded at the end, because only it is a bonus.
      if (perfect) {
        this.addScore(PERFECT_BONUS);
        this.showBanner(`PERFECT!!\nSPECIAL BONUS ${PERFECT_BONUS} PTS`, 2200);
      } else {
        const paid = this.challengingHits * CHALLENGING_STAGE_HIT_POINTS;
        this.showBanner(`NUMBER OF HITS ${this.challengingHits}\nBONUS ${paid} PTS`, 2200);
      }
    }

    this.stageAdvanceTimer = this.time.delayedCall(this.challenging ? 2400 : 1200, () => {
      this.stageAdvanceTimer = null;
      if (this.isGameOver) return;
      this.round += 1;
      this.stage = nextStage(this.stage);
      this.beginStage(this.stage);
    });
  }

  // ---------------------------------------------------------------- attacks

  /**
   * Pump the per-type launch counters.
   *
   * Called every frame once the wave has assembled. The scheduler decides
   * which types launch this frame against the row's active-bomber ceiling,
   * and whether this frame's Zako launch is instead the transform pull --
   * the arcade's schedule-driven trigger, in place of the 15-second timer an
   * earlier revision ran.
   */
  updateAttacks(delta) {
    if (!this.attackActive || this.challenging || this.stageResolving) return;

    // The no-fire lock-up accrues while the last enemies are being dodged
    // rather than shot; see `advanceNoFire` for the conditions.
    if (this.dips.noFireBug && !this.noFire.triggered) {
      this.noFire = advanceNoFire(this.noFire, delta, {
        enabled: true,
        enemiesRemaining: this.enemies.countActive(true),
      });
      if (this.noFire.triggered) this.registry.set('noFireTriggered', true);
    }

    if (!this.captureIsIdle()) return;

    const enemies = this.enemies.getChildren();
    const activeBombers = enemies.filter(isDiving).length;
    const availableTypes = [
      ...new Set(enemies.filter(canBeginDive).map((e) => e.enemyType)),
    ];
    const escortsAvailable = enemies.filter(
      (e) => e.enemyType === EnemyType.GOEI && canBeginDive(e),
    ).length;

    const { state, launches, transformPull } = advanceScheduler(this.attack, delta, {
      activeBombers,
      // The scheduler's live inputs: the reloads and the bomb mask tighten
      // as the board thins and the stage drags, and continuous bombing arms
      // once the count drops below the row's threshold with the player able
      // to fire -- all recomputed every frame, the ROM's f_0857.
      aliveEnemies: this.enemies.countActive(true),
      playerFireActive: this.player.active,
      availableTypes,
      escortsAvailable,
      // The cflag: a held fighter keeps the boss alternation from advancing.
      captureActive: this.captureState === CaptureState.HELD,
      transformStage: Boolean(this.transformType),
    });
    this.attack = state;

    launches.forEach((launch) => this.launchDive(launch));
    if (transformPull) this.triggerTransform();
  }

  scheduleCaptureAttempts() {
    this.captureTimer = this.time.addEvent({
      delay: CAPTURE.attemptIntervalMs,
      loop: true,
      callback: () => this.attemptCapture(),
    });
  }

  /**
   * Pull a Zako out of the grid, pulsate it, and replace it with a bonus trio.
   *
   * Only a Zako is eligible, which is what the arcade does and also what keeps
   * the formation's shape readable: the Goei rows and the boss row stay intact
   * while the bottom of the grid thins out.
   */
  triggerTransform() {
    if (this.isGameOver || this.challenging || !this.transformType) return;
    if (!this.captureIsIdle()) return;

    const eligible = this.enemies
      .getChildren()
      .filter((enemy) => enemy.enemyType === EnemyType.ZAKO && canBeginDive(enemy));
    if (eligible.length === 0) return;

    const chosen = Phaser.Utils.Array.GetRandom(eligible);
    chosen.transforming = true;

    // The pulse is the player's warning. The tween is what decides when the
    // swap happens, so a transform can never fire on a frame where the Zako
    // has already been shot: `onComplete` re-checks that it is still alive.
    this.tweens.add({
      targets: chosen,
      // The ship textures are drawn at scale 1, so the warning pulse is a
      // straight 35% swell rather than a multiple of an authoring scale.
      scale: 1.35,
      duration: TRANSFORM.pulseDurationMs,
      yoyo: true,
      repeat: TRANSFORM.pulseRepeats,
      onComplete: () => {
        if (!chosen.active || this.isGameOver || this.stageResolving) return;
        const origin = { x: chosen.x, y: chosen.y };
        this.destroyEnemy(chosen, false);
        this.spawnTransformSet(origin);
      },
    });
  }

  /**
   * Three bonus ships abreast, each flying its own attack run from where the
   * Zako was standing.
   *
   * They share one `set` object by reference; see `createTransformEnemy`. They
   * are ordinary members of the enemy group, so every collider that already
   * exists applies to them, and they leave off the bottom of the screen on
   * their own if the player does not take them.
   */
  spawnTransformSet(origin) {
    this.sfx.transformSet.play({ volume: 0.5 });
    const set = { type: this.transformType, remaining: TRANSFORM_SET_SIZE };

    for (let i = 0; i < TRANSFORM_SET_SIZE; i += 1) {
      const start = {
        x: origin.x + (i - (TRANSFORM_SET_SIZE - 1) / 2) * TRANSFORM.spacingX,
        y: origin.y,
      };
      const enemy = createTransformEnemy(
        this,
        this.enemies,
        this.transformType,
        start,
        set,
        this.flapFrame,
      );
      // Armed like any attack dive: the mask the scheduler computed this
      // frame from d_0909 and the live board.
      enemy.bombMask = this.enemiesArmed() ? this.attack.bombFlags : 0;
      enemy.bombCountdownMs = BOMB_ARM_FRAMES * FRAME_MS;
      enemy.flight = createFlight(
        divePath(start, this.player.x, SCREEN, { stageIndex: this.round }),
        TRANSFORM.runDurationMs,
      );
    }
  }

  /**
   * True when no beam or capture animation is occupying the board.
   *
   * HELD counts as free. A ship can be held above its captor for the rest of
   * the stage, and treating that as busy would stop every dive until the
   * player shot the captor down.
   */
  captureIsIdle() {
    return (
      this.captureState === CaptureState.IDLE ||
      this.captureState === CaptureState.DUAL ||
      this.captureState === CaptureState.HELD
    );
  }

  /**
   * Launch the one attacker the scheduler emitted this frame.
   *
   * The squad structure now lives in the scheduler: a boss escort sortie
   * arrives as an `escortLeader` launch followed by its `escortWingman`
   * launches on the next frames, the pool's one-per-frame stagger, so this
   * launches exactly one enemy. The pick within the type is random; the
   * arcade scans the formation in object-index order, which Task 5's slot
   * work can refine.
   */
  launchDive(launch) {
    if (this.isGameOver || this.challenging || !this.captureIsIdle()) return;

    const eligible = this.enemies.getChildren().filter(canBeginDive);
    const ofType = eligible.filter((enemy) => enemy.enemyType === launch.type);
    if (ofType.length === 0) return;

    // A boss holding a captured fighter has to actually leave formation for
    // the rescue to be possible at all, so it is weighted to lead the dive
    // rather than waiting for a one-in-four draw.
    const captorLeads =
      launch.type === EnemyType.BOSS &&
      this.captor?.captiveAttached === true &&
      canBeginDive(this.captor) &&
      Math.random() < CAPTURE.captorDiveChance;

    const leader = captorLeads ? this.captor : Phaser.Utils.Array.GetRandom(ofType);
    // Scoring reads the sortie's size off the leader: a boss that brought
    // two wingmen is the 1600-point kill.
    leader.escortCount = launch.wingmen ?? 0;
    this.beginDive(leader);
  }

  beginDive(enemy) {
    if (!canBeginDive(enemy)) return;
    this.beginDiveSound();
    enemy.mode = EnemyMode.DIVING;

    // A captor takes the fighter it is holding down with it, and the fighter
    // fights: rearm it for this run. See `updateCaptive` for the release.
    if (enemy.captiveAttached && this.captive) this.captive.hasBombed = false;

    // Armed at launch, as `j_108A` arms every diver: a 30-frame countdown
    // and the drop bitmask the scheduler computed this frame from d_0909 --
    // the live board decides how many bombs this run carries, not a
    // per-stage allowance. Each set bit is one bomb, released low in the
    // field on the 20-frame spacing.
    enemy.bombMask = this.enemiesArmed() ? this.attack.bombFlags : 0;
    enemy.bombCountdownMs = BOMB_ARM_FRAMES * FRAME_MS;
    // A LIVE flight on the type's own attack table (yellow/red/boss with
    // its entry offset): speed lives in the table's nibbles, the F3/FE
    // hooks read the player every frame, the FA gate loops the pass while
    // the scheduler holds continuous bombing, and the FB tail glides it
    // back onto its slot. Mirroring is the ROM's objectId-bit-1 recompute,
    // stood in by the slot parity until Task 4 assigns real object ids.
    enemy.flight = createLiveFlight(
      createDiveFlightState(enemy.enemyType, { x: enemy.x, y: enemy.y }, SCREEN, {
        negateRotation: (enemy.slot?.index ?? 0) % 2 === 1,
      }),
      SCREEN,
    );
  }

  /**
   * Whether this stage's attackers carry bombs at all.
   *
   * The stage's own flag, and then the no-fire lock-up on top of it: once
   * that has tripped, nothing shoots again until the page is reloaded.
   */
  enemiesArmed() {
    return enemiesBomb(this.stage, this.rank) && !this.noFire.triggered;
  }

  attemptCapture() {
    if (this.isGameOver || this.challenging || !this.captureIsIdle()) return;
    if (!this.player.active) return;
    // Two gates the arcade applies and a clock cannot: the stage has to allow
    // captures at all, and there has to be enough formation left for hunting
    // the captor down to be a plan the player can act on.
    if (!captureAllowed(this.stage, this.enemies.countActive(true), this.rank)) return;

    const bosses = this.enemies
      .getChildren()
      .filter((enemy) => enemy.enemyType === EnemyType.BOSS && canBeginDive(enemy));
    if (bosses.length === 0) return;

    const boss = Phaser.Utils.Array.GetRandom(bosses);
    this.captureState = transition(this.captureState, CaptureEvent.DEPLOY_BEAM);
    if (this.captureState !== CaptureState.BEAM_OPENING) return;

    boss.mode = EnemyMode.DIVING;
    this.captor = boss;
    this.sfx.bossEntrance.play({ volume: 0.5 });

    // Down into the player's half of the field and across toward the player's
    // column, then open the beam. The descent is the tell: it is a markedly
    // different move from the one-loop dive every other attacker makes, and it
    // is the player's warning to get out of the way.
    //
    // The sideways travel is capped, so the boss aims once on the way down
    // rather than tracking. A player who reads the descent and moves can still
    // slip out from under it.
    this.tweens.add({
      targets: boss,
      x: this.aimedBeamX(boss),
      y: CAPTURE.descendToY,
      duration: CAPTURE.descendDurationMs,
      ease: 'Sine.easeInOut',
      onComplete: () => this.openBeam(boss),
    });
  }

  /**
   * Where a descending boss lines its beam up: the player's column, as far as
   * it can reach, and never so far out that the beam hangs off the screen.
   */
  aimedBeamX(boss) {
    const reach = Phaser.Math.Clamp(
      this.player.x - boss.x,
      -CAPTURE.aimTravelPx,
      CAPTURE.aimTravelPx,
    );
    const half = CAPTURE.beamWidth / 2;
    return Phaser.Math.Clamp(boss.x + reach, half, SCREEN.width - half);
  }

  openBeam(boss) {
    if (!boss.active || this.isGameOver) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      return;
    }

    this.sfx.beamOpen.play({ volume: 0.5 });

    // A ripped beam, when a local checkout has one: full-beam frames cycled
    // like the strips would be, revealed by a crop while it unfurls. Without
    // one the fan is drawn strip by strip; either way `this.beam` is the
    // object whose x/y the pull and the demo pilot read.
    const local = localArtFrames('beam');
    if (local && this.textures.exists(local[0])) {
      this.beam = this.add
        .image(boss.x, boss.y + CAPTURE.beamOffsetY, local[0])
        .setOrigin(0.5, 0)
        .setDisplaySize(CAPTURE.beamWidth * 1.4, CAPTURE.beamLength)
        .setAlpha(0.85)
        .setDepth(5);
      this.beamLocalFrames = local;
    } else {
      this.beam = this.add.graphics({ x: boss.x, y: boss.y + CAPTURE.beamOffsetY });
      this.beam.setAlpha(0.85).setDepth(5);
      this.beamLocalFrames = null;
    }

    this.beamPhase = 'opening';
    this.beamPhaseElapsed = 0;
    this.beamTotalElapsed = 0;
    this.drawBeam();

    this.time.delayedCall(CAPTURE.beamOpenMs, () => {
      if (this.captureState === CaptureState.BEAM_OPENING) {
        this.captureState = CaptureState.BEAM_ACTIVE;
      }
      if (this.beamPhase === 'opening') {
        this.beamPhase = 'active';
        this.beamPhaseElapsed = 0;
      }
    });

    this.time.delayedCall(CAPTURE.beamOpenMs + CAPTURE.beamHoldMs, () => this.closeBeam());
  }

  closeBeam() {
    if (!isBeamDangerous(this.captureState)) return;
    this.captureState = transition(this.captureState, CaptureEvent.BEAM_TIMEOUT);

    // The trap is sprung the moment the state machine says so; the furl that
    // follows is only the picture of it closing. The boss does not wait for it.
    if (this.beam) {
      this.beamPhase = 'retracting';
      this.beamPhaseElapsed = 0;
    }

    const boss = this.captor;
    this.captor = null;
    this.sendCaptorHome(boss);
  }

  clearBeam() {
    if (this.beam) {
      this.beam.destroy();
      this.beam = null;
      this.beamLocalFrames = null;
    }
  }

  /**
   * Draw the beam as it stands this frame: the strip fan from
   * `beamStripsAt`, or a local checkout's ripped frames cropped to the same
   * reveal and cycled on the same clock.
   */
  drawBeam() {
    const opts = {
      strips: CAPTURE.beamStrips,
      openMs: CAPTURE.beamOpenMs,
      cycleMs: CAPTURE.beamCycleMs,
      retractMs: CAPTURE.beamRetractMs,
      width: CAPTURE.beamWidth * 1.4,
      length: CAPTURE.beamLength,
    };
    const strips = beamStripsAt(this.beamPhase, this.beamPhaseElapsed, opts);

    if (this.beamLocalFrames) {
      const frame =
        this.beamLocalFrames[
          Math.floor(this.beamTotalElapsed / CAPTURE.beamCycleMs) % this.beamLocalFrames.length
        ];
      if (this.textures.exists(frame)) this.beam.setTexture(frame);
      const source = this.beam.texture.getSourceImage();
      const revealed = strips.length / CAPTURE.beamStrips;
      this.beam.setCrop(0, 0, source.width, source.height * revealed);
      this.beam.setDisplaySize(CAPTURE.beamWidth * 1.4, CAPTURE.beamLength);
      return;
    }

    this.beam.clear();
    for (const strip of strips) {
      this.beam.fillStyle(strip.color, 1);
      this.beam.fillRect(-strip.width / 2, strip.yOffset, strip.width, strip.height);
    }
  }

  /**
   * Fly a boss back to its slot from wherever it stopped.
   *
   * A boss that has deployed a beam is halted low on the field, so it climbs
   * back from there. Handing it `returnPath`, the way a finished diver is
   * handled, would snap it off the top of the screen first, because that path
   * starts above the ceiling.
   */
  sendCaptorHome(boss) {
    if (!boss || !boss.active) return;

    const target = this.slotPosition(boss.slot);
    boss.mode = EnemyMode.RETURNING;

    this.tweens.add({
      targets: boss,
      x: target.x,
      y: target.y,
      duration: DIVE.returnDurationMs,
      ease: 'Sine.easeInOut',
      onComplete: () => settleIntoFormation(boss, this.slotPosition(boss.slot)),
    });
  }

  capturePlayer() {
    this.captureState = transition(this.captureState, CaptureEvent.PLAYER_CAUGHT);
    if (this.captureState !== CaptureState.CAPTURING) return;

    this.sfx.beamCapture.play({ volume: 0.6 });
    this.player.disableBody(true, false);
    this.clearBeam();

    // A dual fighter caught in a beam loses its second ship rather than
    // carrying it up to the boss.
    this.clearDualFighter();

    const boss = this.captor;
    this.tweens.add({
      targets: this.player,
      x: boss ? boss.x : this.player.x,
      y: boss ? boss.y + CAPTURE.captiveOffsetY : 0,
      duration: CAPTURE.captureRiseMs,
      // The cabinet's fighter has one sprite frame and sixteen orientations,
      // so the ride up the beam is a stepped spin, not a smooth turn: the
      // ship clicks through the same stops a diving Goei does.
      onUpdate: (tween) =>
        this.player.setRotation(
          spinAngleAt(tween.progress * CAPTURE.captureRiseMs, CAPTURE.captureRiseMs),
        ),
      onComplete: () => this.onCaptureComplete(),
    });
  }

  onCaptureComplete() {
    this.player.setVisible(false);
    this.player.setAngle(0);
    this.captureState = transition(this.captureState, CaptureEvent.CAPTURE_COMPLETE);
    this.sfx.captured.play({ volume: 0.6 });
    this.showBanner('FIGHTER CAPTURED', 1400);

    const boss = this.captor;
    if (boss && boss.active) {
      this.captive = this.captives
        .create(boss.x, boss.y + CAPTURE.captiveOffsetY, shipTextureKey('captive'))
        .setDepth(6);
      applyShipArt(this.captive, 'captive');
      this.captive.body.setAllowGravity(false);
      boss.captiveAttached = true;

      // The captor rejoins the formation with its prize in tow, so the player
      // can hunt it down. `this.captor` stays set: the held ship is drawn
      // against it every frame from here until one of them is destroyed.
      this.sendCaptorHome(boss);
    }

    this.loseLife();
  }

  /**
   * Fly the held fighter: pinned beneath its captor, or, once it has broken
   * loose, along its own last attack run.
   *
   * A captured Fighter is not a trophy hanging in the grid. It has joined the
   * enemy side, and on the one run where its captor brings it down within
   * reach it fires on the player alongside it. The release point is the same
   * fraction of the run the captor's own bomb uses, so the two shots arrive
   * together and the captor's dive reads as the double threat it is.
   */
  updateCaptive(delta) {
    const captive = this.captive;
    if (!captive) return;

    if (captive.flight) {
      this.advanceCaptiveEscape(captive, delta);
      return;
    }

    if (!this.captor || !this.captor.active) return;
    captive.setPosition(this.captor.x, this.captor.y + CAPTURE.captiveOffsetY);

    // The captor's dives run live on the path machine with no fixed
    // duration, so "far enough into the run" is read off its descent for a
    // live flight and off track progress for a compiled one.
    const committed = (flight) =>
      isLiveFlight(flight)
        ? this.captor.y >= SCREEN.height * 0.35
        : flightProgress(flight) >= DIVE.bombAtProgress;

    const readyToBomb =
      captiveCanBomb(this.captureState, isDiving(this.captor)) &&
      !captive.hasBombed &&
      this.captor.flight &&
      committed(this.captor.flight);

    if (readyToBomb) {
      captive.hasBombed = true;
      this.fireEnemyBullet(captive);
    }
  }

  /**
   * The swoop a captive makes after its captor dies in formation.
   *
   * It gets one shot on the way past, which is what makes taking the wrong
   * shot at a captor cost something rather than merely forfeiting the rescue,
   * and then it leaves through the bottom of the screen for good.
   */
  advanceCaptiveEscape(captive, delta) {
    captive.flight = advanceFlight(captive.flight, delta);
    const { x, y, angle } = flightTransform(captive.flight);
    captive.setPosition(x, y);
    captive.setRotation(quantizeHeading(angle));

    if (!captive.hasBombed && flightProgress(captive.flight) >= DIVE.bombAtProgress) {
      captive.hasBombed = true;
      this.fireEnemyBullet(captive);
    }

    if (isFlightComplete(captive.flight)) this.clearCaptive();
  }

  clearCaptive() {
    if (this.captive) {
      this.captive.destroy();
      this.captive = null;
    }
  }

  clearDualFighter() {
    if (this.dualFighter) {
      this.dualFighter.destroy();
      this.dualFighter = null;
    }
  }

  rescueCaptive() {
    this.captureState = transition(this.captureState, CaptureEvent.CAPTOR_DESTROYED);
    if (this.captureState !== CaptureState.RETURNING) return;

    if (!this.captive) {
      this.captureState = transition(this.captureState, CaptureEvent.DOCK_COMPLETE);
      return;
    }

    this.tweens.add({
      targets: this.captive,
      x: this.player.x + DUAL_FIGHTER_OFFSET_X,
      y: this.player.y,
      duration: CAPTURE.dockDurationMs,
      ease: 'Sine.easeInOut',
      // The freed ship spins down to the dock the same stepped way it spun
      // up the beam, and arrives upright on the last step.
      onUpdate: (tween) =>
        this.captive.setRotation(
          spinAngleAt(tween.progress * CAPTURE.dockDurationMs, CAPTURE.dockDurationMs),
        ),
      onComplete: () => this.dockCaptive(),
    });
  }

  dockCaptive() {
    this.clearCaptive();
    this.captureState = transition(this.captureState, CaptureEvent.DOCK_COMPLETE);

    // The rescued ship can be a second or so in the air, and the player can be
    // killed by something else while it is. That death resets the machine, so
    // the dock no longer lands in DUAL and there is nothing to dock onto:
    // building the sprite anyway left a wingman flying beside a dead player
    // that fired nothing and absorbed nothing.
    if (!hasDualFighter(this.captureState)) return;

    // Created in the wingman group so it carries a body of its own. Twice the
    // firepower for twice the width to be hit across is the whole trade; an
    // image with no body would have made the upgrade free.
    this.dualFighter = this.wingman
      .create(this.player.x + DUAL_FIGHTER_OFFSET_X, this.player.y, shipTextureKey('player'))
      .setDepth(4);
    applyShipArt(this.dualFighter, 'player');
    this.dualFighter.body.setSize(
      this.dualFighter.width * 0.62,
      this.dualFighter.height * 0.62,
      true,
    );
    this.dualFighter.body.setAllowGravity(false);
    this.dualFighter.body.setImmovable(true);

    this.sfx.rescued.play({ volume: 0.6 });
    this.showBanner('DUAL FIGHTER', 1200);
  }

  // ----------------------------------------------------------------- combat

  onEnemyHit(enemy) {
    if (!enemy.active) return;

    this.stats = recordHit(this.stats);

    // A transform bonus ship pays for itself and, on the third kill, for the
    // set. `transformKillPoints` takes the count still alive including this
    // one, so the scene never has to know which kill completes a trio.
    if (enemy.transformSet) {
      const set = enemy.transformSet;
      const points = transformKillPoints(set.type, set.remaining);
      const { x, y } = enemy;
      set.remaining -= 1;
      this.destroyEnemy(enemy, true);

      this.addScore(points);
      // Only the set bonus is worth announcing; 160 on its own is an ordinary
      // kill. The announcement is the cabinet's: the value, in blue, where
      // the third ship died.
      if (set.remaining === 0) this.spawnScorePopup(x, y, points);
      return;
    }

    if (this.challenging) {
      this.challengingHits += 1;
      this.addScore(scoreFor(enemy.enemyType, { challenging: true }));
      this.destroyEnemy(enemy, true);
      return;
    }

    enemy.health -= 1;

    // A Boss Galaga survives its first hit and changes colour to show it.
    if (enemy.health > 0) {
      showBossDamage(enemy, this.flapFrame);
      this.sfx[deathSoundFor(enemy.enemyType, { destroyed: false })].play({ volume: 0.4 });
      return;
    }

    const points = scoreFor(enemy.enemyType, {
      diving: isDiving(enemy),
      escorts: enemy.escortCount ?? 0,
    });
    this.addScore(points);

    // The cabinet's famous blue number: a Boss Galaga shot down mid-dive
    // flashes what it paid -- 400, 800, 1600 with its escorts -- at the spot
    // it died. Formation kills stay silent; the popup is the reward for the
    // harder shot.
    if (enemy.enemyType === EnemyType.BOSS && isDiving(enemy)) {
      this.spawnScorePopup(enemy.x, enemy.y, points);
    }

    // Galaga's rescue rule: the ship only comes back if its captor is shot
    // down on a dive. Read the mode before the sprite is destroyed, and let
    // the pure rule decide, so "diving or not" is the only thing the scene
    // contributes.
    const outcome =
      enemy.captiveAttached === true
        ? resolveCaptorDestroyed(this.captureState, isDiving(enemy))
        : RescueOutcome.NONE;

    this.destroyEnemy(enemy, true);

    if (outcome === RescueOutcome.RESCUED) {
      this.addScore(CAPTURED_FIGHTER_POINTS);
      this.rescueCaptive();
    } else if (outcome === RescueOutcome.CAPTIVE_LOST) {
      this.loseCaptive();
    }
  }

  /**
   * The player shot their own captured fighter.
   *
   * Counts as a hit, pays 1,000, and ends the capture: the captor is unflagged
   * so that killing it later cannot rescue a ship that no longer exists, and
   * the state machine is driven to IDLE through the same `CAPTIVE_DESTROYED`
   * transition the "captor died in formation" path uses.
   */
  onCaptiveShot() {
    if (!this.captive) return;

    this.stats = recordHit(this.stats);

    // The 1,000 is for shooting your *own* fighter -- a ship you could still
    // have won back. Once the captive has broken loose and is diving at the
    // player the capture is already resolved and the ship is gone either way,
    // so shooting it down is just self-defence and pays nothing.
    if (!this.captive.flight) {
      this.addScore(CAPTURED_FIGHTER_POINTS);
      this.spawnScorePopup(this.captive.x, this.captive.y, CAPTURED_FIGHTER_POINTS);
      if (this.captor) this.captor.captiveAttached = false;
      this.captureState = transition(this.captureState, CaptureEvent.CAPTIVE_DESTROYED);
    }

    this.spawnExplosion('enemy', this.captive.x, this.captive.y, SHIP_DRAWN_PX);
    this.sfx.explosion.play({ volume: 0.4 });

    this.clearCaptive();
  }

  /**
   * The captor died in formation, so the ship it was holding turns on the
   * player.
   *
   * The arcade does not simply delete it: the freed captive "will swoop down
   * on you... it will disappear off the bottom of the screen and go away". So
   * it flies one last attack run, with a shot in it, and only then is gone.
   * That run is the cost of taking the wrong shot at a captor; an earlier
   * revision tweened it straight down off the screen, which made shooting a
   * captor in formation free apart from the forfeited rescue.
   */
  loseCaptive() {
    this.captureState = transition(this.captureState, CaptureEvent.CAPTIVE_DESTROYED);
    if (!this.captive) return;

    this.showBanner('FIGHTER LOST', 1400);
    this.captive.hasBombed = false;
    this.captive.flight = createFlight(
      captiveEscapePath({ x: this.captive.x, y: this.captive.y }, this.player.x, SCREEN),
      CAPTURE.captiveEscapeMs,
    );
  }

  /**
   * Play an explosion where something just died, frame by frame.
   *
   * `kind` is `enemy` or `player` -- the two sequences in
   * `EXPLOSION_SPRITES` -- and the sprite is destroyed the moment
   * `explosionFrameAt` reports the sequence done, so a blast can never be
   * left frozen on screen. A local checkout's ripped frames are used
   * whenever they are loaded, at the same drawn size.
   */
  spawnExplosion(kind, x, y, displaySize) {
    const overrideName = kind === 'player' ? 'explosionPlayer' : 'explosionEnemy';
    const local = localArtFrames(overrideName);
    const frames = local?.length ?? frameCount(EXPLOSION_SPRITES[kind]);
    const frameMs =
      kind === 'player' ? ANIMATION.playerExplosionFrameMs : ANIMATION.enemyExplosionFrameMs;
    const textureFor = (frame) =>
      local ? local[frame % local.length] : explosionTextureKey(kind, frame);

    const burst = this.add.sprite(x, y, textureFor(0)).setDepth(7);
    burst.setDisplaySize(displaySize, displaySize);

    let elapsed = 0;
    const timer = this.time.addEvent({
      delay: frameMs,
      repeat: frames,
      callback: () => {
        elapsed += frameMs;
        const frame = explosionFrameAt(frames, frameMs, elapsed);
        if (frame === null) {
          burst.destroy();
          timer.remove();
          return;
        }
        burst.setTexture(textureFor(frame));
        burst.setDisplaySize(displaySize, displaySize);
      },
    });

    return burst;
  }

  destroyEnemy(enemy, withExplosion) {
    if (withExplosion) {
      // A boss dying draws a burst at twice a ship's size, everything else at
      // one ship: the arcade's own proportions for the two.
      this.spawnExplosion(
        'enemy',
        enemy.x,
        enemy.y,
        enemy.enemyType === EnemyType.BOSS ? SHIP_DRAWN_PX * 2 : SHIP_DRAWN_PX,
      );
      // Each rank of enemy has its own cry in the arcade, which is how a
      // player knows what they hit without looking away from their own ship.
      this.sfx[deathSoundFor(enemy.enemyType)].play({ volume: 0.4 });
    }

    if (enemy === this.captor) {
      this.captor = null;
      this.clearBeam();
    }

    enemy.destroy();
  }

  onPlayerHit() {
    // The dual fighter absorbs a hit by reverting to a single ship.
    if (hasDualFighter(this.captureState)) {
      this.captureState = transition(this.captureState, CaptureEvent.DUAL_HIT);
      this.clearDualFighter();
      this.makeInvulnerable(1000);
      return;
    }

    this.sfx.playerDeath.play({ volume: 0.5 });
    // The death blast is authored at 32x32 against the ships' 16x16, so its
    // drawn size is two ships: the loudest thing the screen ever says.
    this.spawnExplosion('player', this.player.x, this.player.y, SHIP_DRAWN_PX * 2);

    this.player.disableBody(true, false);
    this.player.setVisible(false);
    this.loseLife();
  }

  /**
   * The active player lost a ship.
   *
   * In a one-player game this is what it always was: spend a life, respawn, or
   * end the game. In a two-player game it is also the moment the machine
   * changes hands, so the whole decision is deferred to `loseShip` in
   * `players.js` and this reads the answer off it. The three outcomes are
   * different sentences on the screen -- another ship, `GAME OVER PLAYER 1`
   * while player two carries on, or the results screen -- and nothing here
   * decides which; it only draws them.
   */
  loseLife() {
    // Read before the session moves on: this is the player who just died, and
    // by the time `loseShip` has returned, the machine may already belong to
    // somebody else.
    const flyer = this.session.active;

    this.bankTurn();
    const outcome = loseShip(this.session);
    this.session = outcome.session;
    this.lives = Math.max(this.lives - 1, 0);
    this.refreshHud();

    if (outcome.over) {
      this.endGame();
      return;
    }

    // One player is finished but the other is not. Say so, because otherwise
    // the handover looks like an ordinary change of turn and the player who is
    // out never learns that they are.
    if (outcome.retired) {
      this.showBanner(`GAME OVER\n${playerLabel(flyer)}`, 1800);
    }

    this.time.delayedCall(PLAYER.respawnDelayMs, () => {
      if (this.isGameOver) return;
      if (outcome.handedOver) {
        this.handOverTurn();
        return;
      }
      this.respawnPlayer();
    });
  }

  respawnPlayer() {
    // A ship taken before this death is still held above its captor, and the
    // machine has to stay in HELD for shooting that captor down to rescue it.
    // Resetting here unconditionally is what made the dual fighter, and with
    // it the whole point of the capture, unreachable: the held ship was left
    // stranded on screen with no state left that could bring it back.
    if (this.captureState !== CaptureState.HELD) {
      this.captureState = transition(this.captureState, CaptureEvent.RESET);
      // The reset drops DUAL, so the second ship goes with it. Leaving the
      // sprite behind would have flown a wingman that no longer doubled the
      // bullet limit and no longer absorbed a hit.
      this.clearDualFighter();
    }
    this.clearBeam();

    this.player.enableBody(true, SCREEN.width / 2, PLAYER.y, true, true);
    this.player.setAngle(0);
    this.makeInvulnerable(PLAYER.invulnerableMs);

    // The cabinet says READY over every fresh fighter, not only stage one.
    this.showBanner('READY', 900);
  }

  makeInvulnerable(durationMs) {
    this.isInvulnerable = true;
    this.tweens.add({
      targets: this.player,
      alpha: 0.25,
      yoyo: true,
      repeat: Math.max(Math.floor(durationMs / 200) - 1, 0),
      duration: 100,
      onComplete: () => {
        this.player.setAlpha(1);
        this.isInvulnerable = false;
      },
    });
  }

  canBeHurt() {
    return this.player.active && !this.isInvulnerable && !this.isGameOver;
  }

  endGame() {
    this.bankTurn();
    this.isGameOver = true;
    this.clearTimers();
    // The board goes quiet before the results screen speaks. The attack-run
    // loop is stopped by hand because `updateDiveSound` no longer runs once the
    // game is over, and a held loop would play under the whole results screen.
    this.sfx.ambient.stop();
    this.sfx.enemyDive.stop();

    // The machine's own game does not get a results screen and never touches
    // the board: an attract loop that could write to the high-score table would
    // eventually fill it with itself.
    if (this.demo) {
      this.demoTimer?.remove();
      this.time.delayedCall(1600, () => this.endDemo());
      return;
    }

    this.time.delayedCall(1200, () => {
      // The score is banked by the results screen, not here: it is the screen
      // that asks for initials, and a run that made the board has to be written
      // once, with the name attached, rather than saved twice. The pause is
      // what it always was -- bullets already in the air still land during it,
      // and banking early left the results screen showing a score above its own
      // high score.
      this.scene.start('GameOverScene', {
        session: this.session,
        // A run played after the no-fire lock-up was against a machine that
        // could not shoot back; its score does not rank.
        scoreDisqualified: this.noFire.triggered,
      });
    });
  }

  // ----------------------------------------------------------------- update

  update(_time, delta) {
    if (this.isGameOver || this.frozen) return;

    this.updateStarfield(delta);
    this.formationElapsed += delta;

    this.updateFormation(delta);
    this.updateAttacks(delta);
    this.updateDiveSound();
    this.updatePlayer();
    this.updateCaptive(delta);
    this.updateBeam(delta);
    this.cullProjectiles();
    this.checkStageComplete();
  }

  /**
   * Stream the sky, stop it, or run it backwards.
   *
   * The hardware field stops scrolling while no fighter is on the board --
   * between a death and the respawn -- and that stop is the most legible
   * "the world is holding its breath" cue the cabinet has. And for the few
   * frames the tractor beam is hauling the fighter UP, the whole sky
   * reverses with it: the ROM sets a reverse flag when the beam latches
   * (gg1-3.s l_236D) and clears it when the capture completes or the boss
   * is shot out of it (l_2305, l_2327), which is exactly the window our
   * CAPTURING state spans.
   */
  updateStarfield(delta) {
    const speed =
      this.captureState === CaptureState.CAPTURING
        ? STARFIELD_SCROLL.capture
        : this.player.active
          ? STARFIELD_SCROLL.game
          : 0;
    if (this.starfield.rowsPerFrame !== speed) {
      this.starfield = setStarfieldScroll(this.starfield, speed);
    }

    this.starfield = advanceStarfield(this.starfield, delta);
    this.starLayer.clear();
    for (const star of visibleStars(this.starfield, SCREEN)) {
      this.starLayer.fillStyle(star.color, 1);
      this.starLayer.fillRect(star.x, star.y, 2, 2);
    }
  }

  updateFormation(delta) {
    this.currentBreath = breathScaleAt(this.formationElapsed, {
      periodMs: FORMATION.breathPeriodMs,
      amplitude: FORMATION.breathAmplitude,
    });
    this.currentSway = swayOffsetAt(this.formationElapsed, {
      periodMs: FORMATION.swayPeriodMs,
      amplitude: FORMATION.swayAmplitude,
    });

    // One wing-frame read for the whole pass: every alien on the board,
    // parked or diving, flaps on the same beat, which is what the cabinet's
    // shared frame counter did.
    const frame = flapFrameAt(this.formationElapsed);
    const flapped = frame !== this.flapFrame;
    this.flapFrame = frame;

    this.enemies.getChildren().forEach((enemy) => {
      if (!enemy.active) return;

      if (flapped && enemy.artName) {
        applyShipArt(enemy, enemy.artName, { frame });
      }

      if (enemy.flight) {
        this.advanceEnemyFlight(enemy, delta);
        return;
      }

      if (enemy.mode === EnemyMode.IN_FORMATION) {
        const position = this.slotPosition(enemy.slot);
        enemy.setPosition(position.x, position.y);
      }
    });
  }

  /**
   * The live context the path machine's reactive tokens read each frame:
   * the swaying slot for the FB home glide and the F9/F1 re-entries, the
   * player for FE/F3/F4, the difficulty row's F0/EF switches, and the
   * scheduler's continuous-bombing flag for the FA loop gate.
   */
  liveFlightContext(enemy) {
    return {
      playerX: this.player.x,
      homeTarget: enemy.slot ? this.slotPosition(enemy.slot) : undefined,
      stage8Switch: this.difficulty.stage8PathSwitch,
      stage12Switch: this.difficulty.stage12BombingSwitch,
      continuousBombing: this.attack?.continuousBombing ?? false,
    };
  }

  advanceEnemyFlight(enemy, delta) {
    if (isLiveFlight(enemy.flight)) {
      this.advanceLiveEnemyFlight(enemy, delta);
      return;
    }

    enemy.flight = advanceFlight(enemy.flight, delta);
    const { x, y, angle } = flightTransform(enemy.flight);
    enemy.setPosition(x, y);
    // Snapped to the cabinet's sixteen sprite orientations at render time
    // only: the path underneath stays continuous, so nothing about where the
    // enemy is or what it hits changes -- just what the rotation looks like.
    enemy.setRotation(quantizeHeading(angle));

    this.updateEnemyBombs(enemy, delta);

    if (!isFlightComplete(enemy.flight)) return;

    switch (enemy.mode) {
      case EnemyMode.ENTERING:
      case EnemyMode.RETURNING:
        settleIntoFormation(enemy, this.slotPosition(enemy.slot));
        break;

      case EnemyMode.DIVING:
        // Flew off the bottom; come back in from the top.
        enemy.mode = EnemyMode.RETURNING;
        enemy.flight = createFlight(
          returnPath(this.slotPosition(enemy.slot), SCREEN),
          DIVE.returnDurationMs,
        );
        break;

      case EnemyMode.PASSING:
        // Challenging-stage enemies leave for good.
        enemy.destroy();
        break;

      default:
        enemy.flight = null;
    }
  }

  /**
   * One frame of a flight running live on the ROM's path machine: entries
   * flying their blocks onto the swaying grid, and dives running the attack
   * tables against the live player.
   */
  advanceLiveEnemyFlight(enemy, delta) {
    const { flight, events } = advanceLiveFlight(
      enemy.flight,
      delta,
      this.liveFlightContext(enemy),
    );
    enemy.flight = flight;
    const { x, y, angle } = liveFlightTransform(flight);
    enemy.setPosition(x, y);
    enemy.setRotation(quantizeHeading(angle));

    for (const event of events) {
      // F6 free flight re-arms the bomb string on every pass, exactly as
      // j_108A does at launch: the countdown and this frame's d_0909 mask.
      // The capture-aim and clone-split events are Task 5's machines.
      if (event.type === 'armBombs' && this.enemiesArmed()) {
        enemy.bombMask = this.attack.bombFlags;
        enemy.bombCountdownMs = BOMB_ARM_FRAMES * FRAME_MS;
      }
    }

    this.updateEnemyBombs(enemy, delta);

    if (!isLiveFlightDone(enemy.flight)) return;

    if (liveFlightHomed(enemy.flight) && enemy.slot) {
      // The FB glide snapped onto the slot -- entries and finished dives
      // both end here; the dive tables carry their own top re-entry.
      settleIntoFormation(enemy, this.slotPosition(enemy.slot));
    } else if (enemy.slot) {
      // FF with no home: an authored caravan row still selecting one of the
      // token-free fly-through blocks (until Task 4's stream machine).
      // Re-enter from the top, the F8/F9 + FB idiom.
      enemy.mode = EnemyMode.RETURNING;
      enemy.flight = createFlight(
        returnPath(this.slotPosition(enemy.slot), SCREEN),
        DIVE.returnDurationMs,
      );
    } else {
      enemy.destroy();
    }
  }

  /**
   * The ROM's bomb release, not an aim band: the countdown armed at launch
   * expires every 20 frames and shifts the drop bitmask one bit; a
   * shifted-out set bit is a bomb, released only once the bomber is low in
   * the field and the player can be shot at. A set bit is held while the
   * bomber is still high -- the corpus's compensation for a replica
   * descent slower than the Z80's. Dodging works because each bomb's aim
   * is frozen at its drop (see `fireEnemyBullet`).
   *
   * A transform bonus ship flies `PASSING` because it never joins a
   * formation, but it is making an attack run, not a fly-past: the trio is
   * the highest-value target on the board and an unarmed one would be a free
   * 1,480 points. Challenging-stage enemies are `PASSING` too and are the
   * genuinely harmless case; they never have bombs to spend.
   */
  updateEnemyBombs(enemy, delta) {
    const bombing =
      enemy.mode === EnemyMode.DIVING ||
      enemy.mode === EnemyMode.ENTERING ||
      enemy.transformSet !== undefined;
    if (!bombing || enemy.bombMask <= 0) return;

    enemy.bombCountdownMs = (enemy.bombCountdownMs ?? BOMB_ARM_FRAMES * FRAME_MS) - delta;
    if (enemy.bombCountdownMs <= 0) {
      enemy.bombCountdownMs = BOMB_SPACING_FRAMES * FRAME_MS;
      const isLow = enemy.y >= BOMB_DROP_MIN_Y * ROM_TO_SCREEN && this.player.active;
      const { mask, drop } = nextBombDrop(enemy.bombMask, isLow);
      enemy.bombMask = mask;
      if (drop) this.fireEnemyBullet(enemy);
    }
  }

  /**
   * The attack-run sound, held for as long as anything is attacking.
   *
   * In the arcade this runs for the duration of a dive rather than being a
   * one-shot at the moment of launch, which is what makes a screen with four
   * attackers in the air sound different from one with a single Zako on its
   * way down. Started when the first attacker leaves the grid and stopped by
   * `updateFormation` once the sky is clear again, so overlapping dives share
   * one voice instead of stacking a copy per diver.
   */
  beginDiveSound() {
    if (this.sfx.enemyDive.isPlaying) return;
    this.sfx.enemyDive.play({ volume: 0.25, loop: true });
  }

  /** Stop the attack-run loop once nothing is flying at the player. */
  updateDiveSound() {
    if (!this.sfx.enemyDive.isPlaying) return;
    const attacking = this.enemies.getChildren().some((enemy) => enemy.active && isDiving(enemy));
    if (!attacking) this.sfx.enemyDive.stop();
  }

  /**
   * The texture and drawn box for a projectile, local rip or shipped image.
   *
   * A local projectile is sized by display to exactly the box the shipped
   * image's scale produces, so hitboxes and read distance stay identical.
   */
  projectileArt(localName, shippedKey, scale) {
    const local = localArtFrames(localName);
    const key = local && this.textures.exists(local[0]) ? local[0] : shippedKey;
    return { key, drawnPx: SPRITE_SOURCE_PX * scale };
  }

  fireEnemyBullet(enemy) {
    if (this.enemyBullets.countActive(true) >= DIVE.maxBombs) return;

    const art = this.projectileArt('enemyLaser', 'laser', SPRITE_SCALE.laser);
    const bullet = this.enemyBullets.create(enemy.x, enemy.y + 18, art.key);
    bullet.setDisplaySize(art.drawnPx, art.drawnPx);
    bullet.body.setAllowGravity(false);

    this.sfx.enemyFire.play({ volume: 0.2 });
    // The ROM's frozen aimed shot: the bomb falls at the cabinet's fixed
    // rate and its sideways slope is `clamp(+-3, 5 dx/dy)` toward where the
    // player IS at the drop, never updated after -- aimed where you were,
    // which is why moving under a dive is a decision and standing still is
    // not. The slope ratio is scale-invariant; the clamp and fall rate are
    // ROM px/frame, converted through the x3 adapter and the frame rate.
    const vx =
      bombAimVx(this.player.x - bullet.x, this.player.y - bullet.y) * ROM_TO_SCREEN * PATHCODE_FPS;
    const vy = BOMB_FALL_PER_FRAME * ROM_TO_SCREEN * PATHCODE_FPS;
    bullet.setVelocity(vx, vy);
  }

  updatePlayer() {
    if (!this.player.active) return;

    // In a demo the stick is held by `demoInput`, which is a pure function of
    // the board and lives in `src/systems/demo.js`. It drives the same fields a
    // player's keys drive, so nothing downstream of here knows the difference --
    // the demo is subject to the two-shot limit, the beam and everything else.
    // A hand on the keys, a hand on a pad and a finger on the glass all hold
    // the same two-way stick; `mergeHeld` resolves them the way the leaf
    // switches would.
    const held = this.demo
      ? demoInput(this.demoBoard())
      : {
          ...mergeHeld(
            {
              left: this.keys.left.isDown || this.keys.altLeft.isDown,
              right: this.keys.right.isDown || this.keys.altRight.isDown,
            },
            padHeld(this.padState()),
            touchSteer(
              this.steerPointer?.isDown ? this.steerPointer.x : null,
              this.player.x,
            ),
          ),
          fire: false,
        };

    const { left, right } = held;
    if (held.fire) this.fire();
    this.player.setVelocityX(((right ? 1 : 0) - (left ? 1 : 0)) * PLAYER.speed);

    // World bounds stop the *body*, which is deliberately narrower than the
    // frame the ship is drawn in, so on its own it would let the wingtips slide
    // off the edge of the screen. Clamping the sprite keeps the whole fighter
    // visible without widening the hitbox back out.
    // A docked wingman is part of the ship the player is flying, so the pair is
    // clamped together rather than letting the second ship leave the field.
    const halfShip = SHIP_DRAWN_PX / 2;
    const rightLimit =
      SCREEN.width - halfShip - (this.dualFighter ? DUAL_FIGHTER_OFFSET_X : 0);
    this.player.x = Phaser.Math.Clamp(this.player.x, halfShip, rightLimit);

    if (this.dualFighter) {
      this.dualFighter.setPosition(this.player.x + DUAL_FIGHTER_OFFSET_X, this.player.y);
    }
  }

  /**
   * Galaga's two-bullet limit, doubled while the dual fighter is docked. It is
   * the central constraint of the game: it makes the hit-miss ratio meaningful
   * and stops the player from holding down fire.
   *
   * The limit is the *only* gate. There is deliberately no rate-of-fire timer:
   * in the arcade a shot that connects frees its slot immediately, so accurate
   * close-range play is rewarded with a faster gun. A flat cooldown, which an
   * earlier revision had at 180ms, severs that link and is what makes most
   * clones feel sluggish. What stops the player holding down fire is that each
   * miss occupies a slot until it flies off the top of the screen.
   */
  fire() {
    // Fired from a key event rather than from `update`, so this has to check
    // for itself that there is a ship to fire from: a dead player between
    // respawns, a game already over, or a machine the freeze switch has
    // stopped, would otherwise still shoot.
    if (this.isGameOver || this.frozen || !this.player.active) return;
    if (this.bullets.countActive(true) >= bulletLimit(this.captureState)) return;

    this.spawnBullet(this.player.x);
    let shots = 1;

    if (this.dualFighter) {
      this.spawnBullet(this.dualFighter.x);
      shots = 2;
    }

    this.stats = recordShot(this.stats, shots);
    this.sfx[playerShotSound(this.shotIndex)].play({ volume: 0.3 });
    this.shotIndex += 1;
  }

  spawnBullet(x) {
    const art = this.projectileArt('playerLaser', 'bullet', SPRITE_SCALE.bullet);
    const bullet = this.bullets.create(x, this.player.y - 26, art.key);
    bullet.setDisplaySize(art.drawnPx, art.drawnPx);
    bullet.body.setAllowGravity(false);
    bullet.setVelocityY(-PLAYER.bulletSpeed);
  }

  updateBeam(delta) {
    if (!this.beam) return;

    this.beamPhaseElapsed += delta;
    this.beamTotalElapsed += delta;

    if (this.captor && this.captor.active) {
      this.beam.setPosition(this.captor.x, this.captor.y + CAPTURE.beamOffsetY);
    }
    this.drawBeam();

    // The furl plays out where the beam was left and then the object goes.
    if (this.beamPhase === 'retracting') {
      if (this.beamPhaseElapsed >= CAPTURE.beamRetractMs) this.clearBeam();
      return;
    }

    if (!this.captor || !this.captor.active) return;
    if (!isBeamDangerous(this.captureState) || !this.canBeHurt()) return;

    // Inside the beam column: drag the player toward its centre, and capture
    // once they have been pulled far enough up it.
    const withinX = Math.abs(this.player.x - this.beam.x) < CAPTURE.beamWidth / 2;
    const withinY =
      this.player.y > this.beam.y && this.player.y < this.beam.y + CAPTURE.beamLength;
    if (!withinX || !withinY) return;

    const pull = this.beam.x - this.player.x;
    this.player.x += Math.sign(pull) * Math.min(Math.abs(pull), 2);
    this.player.y -= CAPTURE.pullStrength * (delta / 1000);

    if (this.player.y < this.beam.y + CAPTURE.captureDepth) this.capturePlayer();
  }

  cullProjectiles() {
    this.bullets.getChildren().forEach((bullet) => {
      if (bullet.active && bullet.y < -20) bullet.destroy();
    });

    this.enemyBullets.getChildren().forEach((bullet) => {
      if (!bullet.active) return;
      const offScreen =
        bullet.y > SCREEN.height + 20 || bullet.x < -20 || bullet.x > SCREEN.width + 20;
      if (offScreen) bullet.destroy();
    });
  }

  checkStageComplete() {
    if (this.stageResolving || this.enemies.countActive(true) > 0) return;
    // Enemies launch on a stagger, so an empty group during the launch window
    // is not a cleared stage.
    if (this.formationElapsed < 2000) return;
    this.completeStage();
  }

  // ---------------------------------------------------------------- helpers

  slotPosition(slot) {
    const centreX = clampFormationCentre(SCREEN.width / 2, SCREEN.width, {
      spacingX: FORMATION.spacingX,
      breathScale: this.currentBreath,
      margin: FORMATION.margin,
    });

    return slotWorldPosition(slot, {
      centreX,
      topY: FORMATION.topY,
      spacingX: FORMATION.spacingX,
      spacingY: FORMATION.spacingY,
      breathScale: this.currentBreath,
      swayX: this.currentSway,
    });
  }

  addScore(points) {
    const previous = this.score;
    this.score += points;

    const earned = extraLivesEarned(previous, this.score, this.bonusScheme);
    if (earned > 0) {
      this.lives += earned;
      this.showBanner('EXTRA LIFE', 900);
      this.sfx.extraLife.play({ volume: 0.5 });
    }

    if (this.score > this.highScore) this.highScore = this.score;
    this.refreshHud();
  }

  showBanner(text, durationMs) {
    this.bannerText.setText(text).setVisible(true);
    this.time.delayedCall(durationMs, () => this.bannerText.setVisible(false));
  }

  /**
   * A point value printed where the points were earned, the cabinet's way.
   *
   * Small, blue, and short-lived: the arcade flashes 400/800/1600 at the spot
   * a diving boss died and the bonus values where a transform trio finished,
   * and the number is gone again inside a second. Purely visual -- the score
   * was already added by the caller.
   */
  spawnScorePopup(x, y, value) {
    const popup = arcadeText(this, x, y, String(value), { tint: 0x66ccff }).setOrigin(0.5).setDepth(25);
    this.time.delayedCall(1000, () => popup.destroy());
  }

  refreshHud() {
    this.drawScores();
    this.highScoreText.setText(String(this.highScore));
    this.drawLives();
    this.drawFlags();
  }

  /**
   * Both score columns, and the blink that says which of them is live.
   *
   * The active player's column reads the live score; the other reads whatever
   * was banked when their turn ended, so a player watching their opponent can
   * see exactly how far ahead they need to get.
   */
  drawScores() {
    this.session.players.forEach((player, index) => {
      const live = index === this.turnOwner;
      this.playerScores[index].setText(String(live ? this.score : player.score));
    });

    // The blink follows the ship, not the session: it marks who is flying, and
    // through the pause after a death nobody has taken over yet.
    if (this.blinkingColumn === this.turnOwner) return;
    this.blinkingColumn = this.turnOwner;

    this.playerBlinks.forEach((blink, index) => {
      if (index === this.turnOwner) {
        blink.restart();
        return;
      }
      blink.pause();
      this.playerHeadings[index].setAlpha(1);
    });
  }

  drawLives() {
    this.lifeIcons.forEach((icon) => icon.destroy());
    this.lifeIcons = [];

    // Spaced wider than the icons are drawn, so a row of spare ships reads as
    // separate ships rather than one smear, and capped at the number that fits
    // beside the stage flags: a player on a good run can bank more spare ships
    // than the row is wide, and the arcade stops drawing them rather than
    // running them into the flags.
    const shown = Math.min(Math.max(this.lives - 1, 0), LIFE_ICONS_SHOWN);

    for (let i = 0; i < shown; i += 1) {
      const icon = this.add
        .image(
          16 + i * 36,
          SCREEN.height - 14,
          shipTextureKey('player', SHIP_ART.lifeIconPixelSize),
        )
        .setOrigin(0, 1)
        .setDepth(20);

      this.lifeIcons.push(applyShipArt(icon, 'player', { pixelSize: SHIP_ART.lifeIconPixelSize }));
    }
  }

  /**
   * Build one flag texture per denomination.
   *
   * Generated rather than loaded because the repo ships no flag artwork. Each
   * is drawn once into a texture and then instanced as an image, so a stage
   * showing nine flags costs nine sprites rather than nine redraws.
   */
  drawFlags() {
    this.flagIcons.forEach((icon) => icon.destroy());
    this.flagIcons = [];

    // Laid out right to left, highest denomination outermost, which is the
    // order `stageFlags` returns them in.
    let x = SCREEN.width - 12;
    for (const flag of stageFlags(this.stage)) {
      for (let i = 0; i < flag.count; i += 1) {
        // A ripped flag, when the local directory has one, drawn into
        // exactly the box the generated flag occupies.
        const local = localArtFrames(`flag${flag.value}`);
        const key =
          local && this.textures.exists(local[0]) ? local[0] : flagTextureKey(flag.value);
        const icon = this.add.image(x, SCREEN.height - 14, key).setOrigin(1, 1).setDepth(20);
        if (key !== flagTextureKey(flag.value)) {
          icon.setDisplaySize(FLAG_DRAWN_WIDTH, FLAG_ART.height * FLAG_ART.pixelSize);
        }
        this.flagIcons.push(icon);
        // Ones are drawn shoulder to shoulder, as the arcade does; the larger
        // denominations get a little air so the groups stay countable.
        x -= flag.value === 1 ? FLAG_DRAWN_WIDTH + 2 : FLAG_DRAWN_WIDTH + 6;
      }
    }
  }

  clearTimers() {
    this.assemblyTimer?.remove();
    this.assemblyTimer = null;
    this.captureTimer?.remove();
    this.captureTimer = null;
    // The attack scheduler is not a timer, but it stops with them.
    this.attackActive = false;
  }
}
